// packages/vue/src/components/empty/MEmpty.vue
<script setup lang="ts">
import { computed } from "vue";
import {
  emptyClasses,
  emptyHasFigure,
  emptyStyle,
  EMPTY_DESCRIPTION,
  type EmptyProps,
  type EmptySlots,
} from "@shuimo-design/core";

defineOptions({ name: "MEmpty" });

const {
  description = EMPTY_DESCRIPTION,
  imageSize = 120,
  image = "enso",
  seed = 1,
} = defineProps<EmptyProps>();
const slots = defineSlots<EmptySlots>();

// 给了 image 插槽就不生成内置插图；插槽的有无是框架概念，只能在壳里判断，再交给 core 派生
const figure = computed(() => ({ image, imageSize, seed, custom: Boolean(slots.image) }));
</script>

<template>
  <div :class="emptyClasses(figure)" :style="emptyStyle(figure)">
    <div v-if="emptyHasFigure(figure)" class="m-empty__image" aria-hidden="true">
      <slot name="image"><span class="m-empty__figure" /></slot>
    </div>
    <p class="m-empty__description">
      <slot name="description">{{ description }}</slot>
    </p>
    <div v-if="slots.default" class="m-empty__extra"><slot /></div>
  </div>
</template>

// packages/react/src/components/empty/MEmpty.tsx
import type { CSSProperties, ReactNode } from "react";
import {
  emptyClasses,
  emptyHasFigure,
  emptyStyle,
  EMPTY_DESCRIPTION,
  type EmptyProps as CoreEmptyProps,
} from "@shuimo-design/core";

export interface MEmptyProps extends CoreEmptyProps {
  /**
   * 自定义插图，替换内置的（对应 Vue 的 image 插槽）。
   * 叫 figure 不叫 image：image 这个名字已经被"内置插图选哪张"占了
   */
  figure?: ReactNode;
  /** 说明文字，优先于 description（对应 Vue 的 description 插槽） */
  descriptionNode?: ReactNode;
  /** 说明下面的操作区（按钮等） */
  children?: ReactNode;
  className?: string;
  style?: CSSProperties;
}

export function MEmpty(props: MEmptyProps) {
  const { description = EMPTY_DESCRIPTION, imageSize = 120, image = "enso", seed = 1 } = props;
  // 有没有自定义插图是框架概念，只能在壳里判断，再交给 core 派生
  const figure = { image, imageSize, seed, custom: Boolean(props.figure) };

  return (
    <div
      className={[...emptyClasses(figure), props.className].filter(Boolean).join(" ")}
      style={{ ...emptyStyle(figure), ...props.style } as CSSProperties}
    >
      {emptyHasFigure(figure) ? (
        <div className="m-empty__image" aria-hidden="true">
          {props.figure ?? <span className="m-empty__figure" />}
        </div>
      ) : null}
      <p className="m-empty__description">{props.descriptionNode ?? description}</p>
      {props.children ? <div className="m-empty__extra">{props.children}</div> : null}
    </div>
  );
}
