// packages/react/src/components/collapse/MCollapse.tsx
import { useCallback, useMemo, useRef, useState, type CSSProperties, type ReactNode } from "react";
import {
  collapseActiveNames,
  collapseClasses,
  collapseNextModel,
  type CollapseContextValue,
  type CollapseModel,
  type CollapseProps as CoreCollapseProps,
} from "@shuimo-design/core";
import { CollapseContext } from "./context";

export interface MCollapseProps extends CoreCollapseProps {
  /**
   * 受控的展开项；不传就由组件自己记（配合 defaultValue）。
   * 手风琴下是单个 name（全收起是 undefined），否则是 name 数组。
   */
  value?: CollapseModel;
  defaultValue?: CollapseModel;
  onValueChange?: (value: CollapseModel) => void;
  /** 展开项变化 */
  onChange?: (value: CollapseModel) => void;
  children?: ReactNode;
  className?: string;
  style?: CSSProperties;
}

export function MCollapse(props: MCollapseProps) {
  const { accordion = false, divider = true, disabled = false, children } = props;

  // 受控 / 非受控两种都支持：传了 value 就听外面的，没传就自己记一份
  const isControlled = props.value !== undefined;
  const [uncontrolled, setUncontrolled] = useState<CollapseModel>(props.defaultValue);
  const model = isControlled ? props.value : uncontrolled;

  // toggle 要放进上下文，身份必须稳定（变一次所有子项白重渲染一轮），
  // 但它又得读到最新的值和回调 —— 所以最新的那份挂在 ref 上，闭包里不捕获
  const latest = useRef({ model, isControlled, accordion, props });
  latest.current = { model, isControlled, accordion, props };

  const toggle = useCallback((name: Parameters<CollapseContextValue["toggle"]>[0]) => {
    const current = latest.current;
    // 增删规则（含手风琴只留一项）在 core，和 Vue 那边是同一份
    const next = collapseNextModel(current.model, name, current.accordion);
    if (!current.isControlled) setUncontrolled(next);
    current.props.onValueChange?.(next);
    current.props.onChange?.(next);
  }, []);

  const active = useMemo(() => collapseActiveNames(model), [model]);
  const context = useMemo<CollapseContextValue>(
    () => ({ active, divider, disabled, toggle }),
    [active, divider, disabled, toggle],
  );

  return (
    <CollapseContext value={context}>
      <div
        className={[...collapseClasses({ disabled }), props.className].filter(Boolean).join(" ")}
        style={props.style}
      >
        {children}
      </div>
    </CollapseContext>
  );
}

// packages/vue/src/components/collapse/MCollapse.vue
<script setup lang="ts">
import { computed, provide } from "vue";
import {
  collapseActiveNames,
  collapseClasses,
  collapseNextModel,
  type CollapseContextValue,
  type CollapseEmits,
  type CollapseName,
  type CollapseProps,
  type CollapseSlots,
} from "@shuimo-design/core";
import { collapseKey } from "./context";

defineOptions({ name: "MCollapse" });

const { accordion = false, divider = true, disabled = false } = defineProps<CollapseProps>();
const emit = defineEmits<CollapseEmits>();
defineSlots<CollapseSlots>();
// 手风琴下是单个 name，普通模式下是 name 数组；两种形状的换算在 core 里
const model = defineModel<CollapseName | CollapseName[]>();

function toggle(name: CollapseName) {
  const next = collapseNextModel(model.value, name, accordion);
  model.value = next;
  emit("change", next);
}

// 上下文装成 computed：展开项 / divider / 禁用任一变了，读它的子项跟着重渲染
provide(
  collapseKey,
  computed<CollapseContextValue>(() => ({
    active: collapseActiveNames(model.value),
    divider,
    disabled,
    toggle,
  })),
);
</script>

<template>
  <div :class="collapseClasses({ disabled })">
    <slot />
  </div>
</template>
