// packages/vue/src/components/select/MSelect.vue
<script setup lang="ts">
import { computed, useId, useTemplateRef, watch } from "vue";
import {
  createSelect,
  selectActiveId,
  selectClasses,
  selectHasSearch,
  selectIsSelected,
  selectOptionClasses,
  selectOptionId,
  selectSearchPlaceholder,
  selectSearchValue,
  selectShowClear,
  selectView,
  SELECT_CLEAR_LABEL,
  SELECT_DROPDOWN_BRUSH,
  SELECT_EMPTY_TEXT,
  SELECT_LOADING_TEXT,
  SELECT_MAX_HEIGHT,
  SELECT_PLACEHOLDER,
  SELECT_TRIGGER_BRUSH,
  type SelectEmits,
  type SelectNormalizedOption,
  type SelectProps,
  type SelectSlots,
  type SelectValue,
} from "@shuimo-design/core";
import { IconCheck, IconChevronDown, IconClose, IconLoading } from "../../icons";
import { useDisabled, useFormItem } from "../../internal/form-item";
import { useBrushBorder } from "../../ink";
import MPopper from "../../internal/popper/MPopper.vue";
import { MTag } from "../tag";
import { useController } from "../../runtime";

defineOptions({ name: "MSelect" });

const {
  options,
  optionParam,
  valueParam,
  inputParam,
  toMatch,
  placeholder = SELECT_PLACEHOLDER,
  disabled: disabledProp = false,
  clearable = false,
  multiple = false,
  filterable = false,
  filter,
  loading = false,
  fetch,
  emptyText = SELECT_EMPTY_TEXT,
  maxHeight = SELECT_MAX_HEIGHT,
  teleport = true,
} = defineProps<SelectProps>();
const emit = defineEmits<SelectEmits>();
const slots = defineSlots<SelectSlots>();
// 值类型里带 boolean 会触发 Vue 的布尔转换，不传就变成 false；显式给个 undefined 默认值挡掉
const model = defineModel<SelectValue | SelectValue[] | undefined>({ default: undefined });

const formItem = useFormItem();
const disabled = useDisabled(() => disabledProp);
const listboxId = useId();
const root = useTemplateRef<HTMLElement>("root");
const trigger = useTemplateRef<HTMLElement>("trigger");
// 触发器和输入框共用一套细笔触参数，同一张表单里边框粗细才一致
useBrushBorder(trigger, SELECT_TRIGGER_BRUSH);
// 下拉面板被 Teleport 到 body，边框要套在面板容器自己身上；面板每次打开都是新元素，useBrushBorder 会重新落笔
const dropdown = useTemplateRef<HTMLElement>("dropdown");
useBrushBorder(dropdown, SELECT_DROPDOWN_BRUSH);
const search = useTemplateRef<HTMLInputElement>("search");
const list = useTemplateRef<HTMLElement>("list");

// 展开、聚焦、过滤文字、高亮项、正在拉下一页全在 core 的控制器里，React 那边用的是同一份
const { controller: select, state } = useController(createSelect, () => ({
  options,
  optionParam,
  valueParam,
  inputParam,
  toMatch,
  filter,
  filterable,
  multiple,
  disabled: disabled.value,
  value: model.value,
  fetch,
  onCommit: (next: SelectValue | SelectValue[] | undefined) => {
    model.value = next;
    emit("change", next);
    formItem.value.validate("change");
  },
  onSelect: (option: SelectProps["options"][number]) => emit("select", option),
  onInput: (value: string) => emit("input", value),
  onVisibleChange: (open: boolean) => emit("visibleChange", open),
  onRemoveTag: (value: SelectValue) => emit("removeTag", value),
  onClear: () => emit("clear"),
  onFocus: (event: FocusEvent) => emit("focus", event),
  onBlur: (event: FocusEvent) => {
    emit("blur", event);
    formItem.value.validate("blur");
  },
}));

watch(
  [root, trigger, search, list],
  () => {
    select.setRoot(root.value);
    select.setTrigger(trigger.value);
    select.setSearch(search.value);
    select.setList(list.value);
  },
  { immediate: true, flush: "post" },
);
// 高亮换了要把那一项滚进视野；flush: "post" 才等得到这一轮 DOM 更新
watch(
  () => state.value.activeIndex,
  () => select.scrollActiveIntoView(),
  { flush: "post" },
);

// 归一化、过滤、选中判断一次算完；控制器内部处理键盘时调的是同一个 selectView
const view = computed(() =>
  selectView({
    options,
    optionParam,
    valueParam,
    inputParam,
    toMatch,
    filter,
    filterable,
    multiple,
    value: model.value,
    query: state.value.query,
  }),
);
const open = computed(() => state.value.open);
const hasSearch = computed(() => selectHasSearch({ multiple, filterable }));
const showClear = computed(() =>
  selectShowClear({ clearable, disabled: disabled.value, hasValue: view.value.hasValue }),
);
const searchValue = computed(() =>
  selectSearchValue({
    multiple,
    open: open.value,
    query: state.value.query,
    singleLabel: view.value.singleLabel,
  }),
);
const searchPlaceholder = computed(() =>
  selectSearchPlaceholder({
    multiple,
    open: open.value,
    hasValue: view.value.hasValue,
    singleLabel: view.value.singleLabel,
    placeholder,
  }),
);
const activeId = computed(() => selectActiveId(listboxId, state.value));

function isSelected(option: SelectNormalizedOption) {
  return selectIsSelected(option, view.value.selectedValues, toMatch);
}
</script>

<template>
  <div
    ref="root"
    :class="
      selectClasses({
        open,
        focused: state.focused,
        disabled,
        multiple,
        filterable,
      })
    "
    @focusin="select.onFocusin"
    @focusout="select.onFocusout"
    @keydown="select.onKeydown"
  >
    <div
      :id="formItem.id"
      ref="trigger"
      class="m-select__trigger"
      role="combobox"
      :aria-expanded="open"
      aria-haspopup="listbox"
      :aria-controls="listboxId"
      :aria-activedescendant="activeId"
      :aria-disabled="disabled || undefined"
      :tabindex="disabled ? -1 : 0"
      @click="select.onTriggerClick"
      @focus="select.onTriggerFocus"
    >
      <span v-if="slots.prefix" class="m-select__prefix"><slot name="prefix" /></span>
      <div class="m-select__content">
        <template v-if="multiple">
          <MTag
            v-for="option in view.selectedOptions"
            :key="option.key"
            class="m-select__tag"
            size="sm"
            closable
            :disabled="disabled"
            @close="select.removeTag(option.value)"
          >
            {{ option.inputLabel }}
          </MTag>
        </template>
        <span
          v-else-if="!filterable"
          class="m-select__label"
          :class="{ 'm-select__placeholder': !view.hasValue }"
        >
          {{ view.hasValue ? view.singleLabel : placeholder }}
        </span>
        <input
          v-if="hasSearch"
          ref="search"
          class="m-select__search"
          type="text"
          autocomplete="off"
          tabindex="-1"
          :value="searchValue"
          :placeholder="searchPlaceholder"
          :readonly="!filterable"
          :disabled="disabled"
          @input="select.onSearchInput"
        />
      </div>
      <span class="m-select__suffix">
        <button
          v-if="showClear"
          type="button"
          class="m-select__clear"
          :aria-label="SELECT_CLEAR_LABEL"
          tabindex="-1"
          @mousedown.prevent
          @click.stop="select.clear()"
        >
          <IconClose />
        </button>
        <span class="m-select__arrow" aria-hidden="true">
          <IconChevronDown class="m-select__arrow-icon" />
          <span class="m-select__arrow-ink" />
        </span>
      </span>
    </div>
    <MPopper
      :open="open"
      :reference="root"
      match-width
      role="listbox"
      :teleport="teleport"
      @click-outside="select.onClickOutside"
    >
      <div ref="dropdown" class="m-select__dropdown" @mousedown.prevent>
        <div v-if="loading" class="m-select__loading">
          <IconLoading /><span>{{ SELECT_LOADING_TEXT }}</span>
        </div>
        <ul
          v-else-if="view.visible.length"
          :id="listboxId"
          ref="list"
          class="m-select__options"
          role="presentation"
          :style="{ maxHeight: `${maxHeight}px` }"
          @scroll.passive="select.onListScroll"
        >
          <li
            v-for="(option, index) in view.visible"
            :id="selectOptionId(listboxId, index)"
            :key="option.key"
            :class="
              selectOptionClasses({
                active: index === state.activeIndex,
                selected: isSelected(option),
                disabled: option.disabled,
              })
            "
            role="option"
            :aria-selected="isSelected(option)"
            :aria-disabled="option.disabled || undefined"
            @click="select.choose(option)"
            @mousemove="select.setActiveIndex(index)"
          >
            <slot
              name="option"
              :option="option.raw"
              :label="option.label"
              :selected="isSelected(option)"
            >
              <span class="m-select__option-label">{{ option.label }}</span>
            </slot>
            <IconCheck v-if="multiple && isSelected(option)" class="m-select__check" />
          </li>
          <li v-if="state.fetching" class="m-select__fetching" role="presentation">
            <IconLoading />
          </li>
        </ul>
        <div v-else class="m-select__empty">
          <slot name="empty">{{ emptyText }}</slot>
        </div>
      </div>
    </MPopper>
  </div>
</template>

// packages/react/src/components/select/MSelect.tsx
import { useCallback, useEffect, useId, useState, type CSSProperties, type ReactNode } from "react";
import {
  createSelect,
  selectActiveId,
  selectClasses,
  selectHasSearch,
  selectIsSelected,
  selectOptionClasses,
  selectOptionId,
  selectSearchPlaceholder,
  selectSearchValue,
  selectShowClear,
  selectView,
  SELECT_CLEAR_LABEL,
  SELECT_DROPDOWN_BRUSH,
  SELECT_EMPTY_TEXT,
  SELECT_LOADING_TEXT,
  SELECT_MAX_HEIGHT,
  SELECT_PLACEHOLDER,
  SELECT_TRIGGER_BRUSH,
  type SelectNormalizedOption,
  type SelectOptionLike,
  type SelectOptionScope,
  type SelectProps as CoreSelectProps,
  type SelectValue,
} from "@shuimo-design/core";
import { IconCheck, IconChevronDown, IconClose, IconLoading } from "../../icons";
import { useBrushBorder } from "../../ink";
import { MPopper } from "../../internal/MPopper";
import { MTag } from "../tag";
import { useController } from "../../runtime";

export interface MSelectProps extends CoreSelectProps {
  /** 受控值；不传就由组件自己记（配合 defaultValue） */
  value?: SelectValue | SelectValue[];
  defaultValue?: SelectValue | SelectValue[];
  onValueChange?: (value: SelectValue | SelectValue[] | undefined) => void;
  /** 选中值变化 */
  onChange?: (value: SelectValue | SelectValue[] | undefined) => void;
  /** 点选了某个选项，参数是原始选项（多选时取消勾选也会触发） */
  onSelect?: (option: SelectOptionLike) => void;
  /** 过滤框里的文字变化 */
  onInput?: (value: string) => void;
  /** 下拉开合 */
  onVisibleChange?: (open: boolean) => void;
  /** 多选时点了 Tag 的关闭 */
  onRemoveTag?: (value: SelectValue) => void;
  /** 点了清空按钮 */
  onClear?: () => void;
  onFocus?: (event: FocusEvent) => void;
  onBlur?: (event: FocusEvent) => void;
  /** 自定义选项内容，对应 Vue 的 `#option="{ option, label, selected }"` 作用域插槽 */
  renderOption?: (scope: SelectOptionScope) => ReactNode;
  /** 无数据时的内容 */
  empty?: ReactNode;
  /** 触发区前的内容（图标） */
  prefix?: ReactNode;
  className?: string;
  style?: CSSProperties;
}

export function MSelect(props: MSelectProps) {
  const {
    options,
    optionParam,
    valueParam,
    inputParam,
    toMatch,
    placeholder = SELECT_PLACEHOLDER,
    disabled = false,
    clearable = false,
    multiple = false,
    filterable = false,
    filter,
    loading = false,
    fetch,
    emptyText = SELECT_EMPTY_TEXT,
    maxHeight = SELECT_MAX_HEIGHT,
    teleport = true,
    renderOption,
    empty,
    prefix,
  } = props;

  // 受控与否看的是有没有传 `value` 这个键，不是它等不等于 undefined：
  // 单选清空之后值本来就是 undefined，用 `!== undefined` 判断会让受控的选择器清空后突然变成非受控
  const controlled = "value" in props;
  const [uncontrolled, setUncontrolled] = useState<SelectValue | SelectValue[] | undefined>(
    props.defaultValue,
  );
  const model = controlled ? props.value : uncontrolled;

  const listboxId = useId();

  // 展开、聚焦、过滤文字、高亮项、正在拉下一页全在 core 的控制器里，和 Vue 那边同一份
  const [select, state] = useController(createSelect, {
    options,
    optionParam,
    valueParam,
    inputParam,
    toMatch,
    filter,
    filterable,
    multiple,
    disabled,
    value: model,
    fetch,
    onCommit: (next: SelectValue | SelectValue[] | undefined) => {
      if (!controlled) setUncontrolled(next);
      props.onValueChange?.(next);
      props.onChange?.(next);
    },
    onSelect: (option: SelectOptionLike) => props.onSelect?.(option),
    onInput: (value: string) => props.onInput?.(value),
    onVisibleChange: (open: boolean) => props.onVisibleChange?.(open),
    onRemoveTag: (value: SelectValue) => props.onRemoveTag?.(value),
    onClear: () => props.onClear?.(),
    onFocus: (event: FocusEvent) => props.onFocus?.(event),
    onBlur: (event: FocusEvent) => props.onBlur?.(event),
  });

  // 触发器和输入框共用一套细笔触参数，同一张表单里边框粗细才一致
  const triggerBrush = useBrushBorder(SELECT_TRIGGER_BRUSH);
  // 下拉面板被传送到 body，边框要套在面板容器自己身上；面板每次打开都是新元素，控制器会重新落笔
  const dropdownBrush = useBrushBorder(SELECT_DROPDOWN_BRUSH);

  // 根元素既是控制器判断「焦点还在不在组件里」的依据，也是下拉的定位参照，所以要进 state
  const [rootEl, setRootEl] = useState<HTMLElement | null>(null);
  // ref 回调的身份必须稳定：变了 React 会先 ref(null) 再 ref(node)，控制器手里的元素会来回换
  const rootRef = useCallback(
    (el: HTMLElement | null) => {
      setRootEl(el);
      select.setRoot(el);
    },
    [select],
  );
  const triggerRef = useCallback(
    (el: HTMLElement | null) => {
      triggerBrush(el);
      select.setTrigger(el);
    },
    [triggerBrush, select],
  );
  const searchRef = useCallback((el: HTMLInputElement | null) => select.setSearch(el), [select]);
  const listRef = useCallback((el: HTMLElement | null) => select.setList(el), [select]);

  // 高亮换了要把那一项滚进视野；useEffect 跑在 DOM 提交之后，等价于 Vue 的 flush: "post"
  useEffect(() => select.scrollActiveIntoView(), [select, state.activeIndex]);

  // 归一化、过滤、选中判断一次算完；控制器内部处理键盘时调的是同一个 selectView
  const view = selectView({
    options,
    optionParam,
    valueParam,
    inputParam,
    toMatch,
    filter,
    filterable,
    multiple,
    value: model,
    query: state.query,
  });
  const open = state.open;
  const isSelected = (option: SelectNormalizedOption) =>
    selectIsSelected(option, view.selectedValues, toMatch);

  return (
    <div
      ref={rootRef}
      className={[
        ...selectClasses({ open, focused: state.focused, disabled, multiple, filterable }),
        props.className,
      ]
        .filter(Boolean)
        .join(" ")}
      style={props.style}
      onFocus={(e) => select.onFocusin(e.nativeEvent)}
      onBlur={(e) => select.onFocusout(e.nativeEvent)}
      onKeyDown={(e) => select.onKeydown(e.nativeEvent)}
    >
      <div
        ref={triggerRef}
        className="m-select__trigger"
        role="combobox"
        aria-expanded={open}
        aria-haspopup="listbox"
        aria-controls={listboxId}
        aria-activedescendant={selectActiveId(listboxId, state)}
        aria-disabled={disabled || undefined}
        tabIndex={disabled ? -1 : 0}
        onClick={(e) => select.onTriggerClick(e.nativeEvent)}
        onFocus={(e) => select.onTriggerFocus(e.nativeEvent)}
      >
        {prefix ? <span className="m-select__prefix">{prefix}</span> : null}
        <div className="m-select__content">
          {multiple
            ? view.selectedOptions.map((option) => (
                <MTag
                  key={option.key}
                  className="m-select__tag"
                  size="sm"
                  closable
                  disabled={disabled}
                  onClose={() => select.removeTag(option.value)}
                >
                  {option.inputLabel}
                </MTag>
              ))
            : null}
          {!multiple && !filterable ? (
            <span
              className={["m-select__label", view.hasValue ? "" : "m-select__placeholder"]
                .filter(Boolean)
                .join(" ")}
            >
              {view.hasValue ? view.singleLabel : placeholder}
            </span>
          ) : null}
          {selectHasSearch({ multiple, filterable }) ? (
            <input
              ref={searchRef}
              className="m-select__search"
              type="text"
              autoComplete="off"
              tabIndex={-1}
              value={selectSearchValue({
                multiple,
                open,
                query: state.query,
                singleLabel: view.singleLabel,
              })}
              placeholder={selectSearchPlaceholder({
                multiple,
                open,
                hasValue: view.hasValue,
                singleLabel: view.singleLabel,
                placeholder,
              })}
              readOnly={!filterable}
              disabled={disabled}
              onChange={(e) => select.onSearchInput(e.nativeEvent)}
            />
          ) : null}
        </div>
        <span className="m-select__suffix">
          {selectShowClear({ clearable, disabled, hasValue: view.hasValue }) ? (
            <button
              type="button"
              className="m-select__clear"
              aria-label={SELECT_CLEAR_LABEL}
              tabIndex={-1}
              onMouseDown={(e) => e.preventDefault()}
              onClick={(e) => {
                e.stopPropagation();
                select.clear();
              }}
            >
              <IconClose />
            </button>
          ) : null}
          <span className="m-select__arrow" aria-hidden="true">
            <IconChevronDown className="m-select__arrow-icon" />
            <span className="m-select__arrow-ink" />
          </span>
        </span>
      </div>
      <MPopper
        open={open}
        reference={rootEl}
        matchWidth
        role="listbox"
        teleport={teleport}
        onClickOutside={select.onClickOutside}
      >
        <div
          ref={dropdownBrush}
          className="m-select__dropdown"
          onMouseDown={(e) => e.preventDefault()}
        >
          {loading ? (
            <div className="m-select__loading">
              <IconLoading />
              <span>{SELECT_LOADING_TEXT}</span>
            </div>
          ) : view.visible.length > 0 ? (
            <ul
              id={listboxId}
              ref={listRef}
              className="m-select__options"
              role="presentation"
              style={{ maxHeight: `${maxHeight}px` }}
              onScroll={select.onListScroll}
            >
              {view.visible.map((option, index) => {
                const selected = isSelected(option);
                const scope: SelectOptionScope = {
                  option: option.raw,
                  label: option.label,
                  selected,
                };
                return (
                  <li
                    key={option.key}
                    id={selectOptionId(listboxId, index)}
                    className={selectOptionClasses({
                      active: index === state.activeIndex,
                      selected,
                      disabled: option.disabled,
                    }).join(" ")}
                    role="option"
                    aria-selected={selected}
                    aria-disabled={option.disabled || undefined}
                    onClick={() => select.choose(option)}
                    onMouseMove={() => select.setActiveIndex(index)}
                  >
                    {renderOption ? (
                      renderOption(scope)
                    ) : (
                      <span className="m-select__option-label">{option.label}</span>
                    )}
                    {multiple && selected ? <IconCheck className="m-select__check" /> : null}
                  </li>
                );
              })}
              {state.fetching ? (
                <li className="m-select__fetching" role="presentation">
                  <IconLoading />
                </li>
              ) : null}
            </ul>
          ) : (
            <div className="m-select__empty">{empty ?? emptyText}</div>
          )}
        </div>
      </MPopper>
    </div>
  );
}
