// packages/react/src/components/printer/MPrinter.tsx
import { useEffect, useImperativeHandle, type CSSProperties, type Ref } from "react";
import {
  createTypewriter,
  printerClasses,
  type PrinterProps as CorePrinterProps,
} from "@shuimo-design/core";
import { useController } from "../../runtime";

/** 命令式的两个口子：ref 拿到的就是它 */
export interface MPrinterHandle {
  /** 从头再打一遍 */
  restart(): void;
  /** 跳到结尾，直接显示全文 */
  finish(): void;
}

export interface MPrinterProps extends CorePrinterProps {
  /** 一段文字全部打完时触发；循环时每一轮都会触发 */
  onEnd?: () => void;
  className?: string;
  style?: CSSProperties;
  ref?: Ref<MPrinterHandle>;
}

export function MPrinter(props: MPrinterProps) {
  const { text = "", cursor = true } = props;

  // 定时器、码点切分、循环、结束回调全在 core 的控制器里，这里只负责喂参数和拿快照
  const [controller, state] = useController(createTypewriter, {
    text,
    speed: props.speed,
    loop: props.loop,
    pause: props.pause,
    autoplay: props.autoplay,
    onEnd: props.onEnd,
  });

  // 每次渲染之后提醒控制器对一次印文：换了就从头再打。换没换由 core 自己比，壳里不留状态
  useEffect(() => {
    controller.refresh();
  });

  useImperativeHandle(
    props.ref,
    () => ({ restart: () => controller.restart(), finish: () => controller.finish() }),
    [controller],
  );

  return (
    <span
      className={[...printerClasses(state.done), props.className].filter(Boolean).join(" ")}
      style={props.style}
      aria-label={text}
    >
      <span className="m-printer__text" aria-hidden="true">
        {state.shown}
      </span>
      {cursor ? <span className="m-printer__cursor" aria-hidden="true" /> : null}
    </span>
  );
}

// packages/vue/src/components/printer/MPrinter.vue
<script setup lang="ts">
import { watch } from "vue";
import {
  createTypewriter,
  printerClasses,
  type PrinterEmits,
  type PrinterProps,
} from "@shuimo-design/core";
import { useController } from "../../runtime";

defineOptions({ name: "MPrinter" });

const {
  text = "",
  speed,
  pause,
  // 这三个必须直接从 defineProps() 上解构并写默认值：类型是 boolean，
  // Vue 会做 Boolean 转型，不写 default 的话"不传"会变成 false
  loop = false,
  cursor = true,
  autoplay = true,
} = defineProps<PrinterProps>();
const emit = defineEmits<PrinterEmits>();

// 定时器、码点切分、循环、结束回调全在 core 的控制器里，这里只负责喂参数和拿快照
const { controller, state } = useController(createTypewriter, () => ({
  text,
  speed,
  loop,
  pause,
  autoplay,
  onEnd: () => emit("end"),
}));

// 印文换了就从头再打；换没换由控制器自己比，这里只管在 DOM 更新之后提醒它一声
watch(
  () => text,
  () => controller.refresh(),
  { flush: "post" },
);

defineExpose({
  restart: () => controller.restart(),
  finish: () => controller.finish(),
});
</script>

<template>
  <span :class="printerClasses(state.done)" :aria-label="text">
    <span class="m-printer__text" aria-hidden="true">{{ state.shown }}</span>
    <span v-if="cursor" class="m-printer__cursor" aria-hidden="true" />
  </span>
</template>
