// packages/vue/src/components/card/MCard.vue
<script setup lang="ts">
import {
  computed,
  onMounted,
  onScopeDispose,
  reactive,
  ref,
  useTemplateRef,
  watch,
  watchEffect,
  watchPostEffect,
} from "vue";
import {
  cardBrush,
  cardClasses,
  cardDividerLine,
  cardInk,
  createCardDivider,
  ensureCardSheet,
  observeSize,
  type CardProps,
  type CardSlots,
} from "@shuimo-design/core";
import { useBrushBorder } from "../../ink";

defineOptions({ name: "MCard" });

const {
  // bordered 必须直接从 defineProps() 上解构并写默认值：类型是 boolean，
  // Vue 会做 Boolean 转型，不写 default 的话"不传"会变成 false
  bordered = true,
  title,
  shadow,
  frame,
  padding,
  seed,
} = defineProps<CardProps>();
const slots = defineSlots<CardSlots>();

/** 转型过的这份 props 才是 core 的输入；其余默认值由 core 归一化，两个壳共用一份 */
const props = computed<CardProps>(() => ({ title, shadow, bordered, frame, padding, seed }));
const hasHeader = computed(() => Boolean(slots.header || slots.extra || title));

const root = useTemplateRef<HTMLElement>("root");
// useBrushBorder 内部用 watchEffect 读这个对象，所以它必须是响应式的
const brush = computed(() => cardBrush(props.value));
const brushOptions = reactive({ ...brush.value });
watchEffect(() => Object.assign(brushOptions, brush.value));
const { update: redrawBorder } = useBrushBorder(root, brushOptions);
// 框型 / 种子换了，元素尺寸没变，控制器不会自己重新落笔，得推一把
watch(brush, () => redrawBorder(), { flush: "post" });

// 纸缘遮罩要按卡片实际尺寸生成，只能挂载后量；服务端和水合首帧都是 0×0，渲染的是没有纸的朴素版
const size = ref({ width: 0, height: 0 });
const mounted = ref(false);
onMounted(() => {
  mounted.value = true;
  if (root.value) observeSize(root.value, (box) => (size.value = box), "border-box");
  ensureCardSheet();
});

const ink = computed(() =>
  cardInk({
    seed,
    padding,
    width: size.value.width,
    height: size.value.height,
    mounted: mounted.value,
  }),
);

// 头部和内容之间那条线按卡片实际宽度单独生成；有没有头部是条件渲染的，元素换了要重新接
const divider = useTemplateRef<HTMLElement>("divider");
const dividerLine = createCardDivider(seed);
watchPostEffect(() => {
  dividerLine.attach(divider.value);
  dividerLine.update(cardDividerLine(seed));
});
onScopeDispose(() => dividerLine.dispose());
</script>

<template>
  <div
    ref="root"
    :class="[...cardClasses(props, Boolean(slots.cover))]"
    :style="ink.style"
    v-bind="ink.attrs"
  >
    <div v-if="slots.cover" class="m-card__cover">
      <slot name="cover" />
    </div>
    <div v-if="hasHeader" class="m-card__header">
      <div class="m-card__title">
        <slot name="header">{{ title }}</slot>
      </div>
      <div v-if="slots.extra" class="m-card__extra">
        <slot name="extra" />
      </div>
    </div>
    <div v-if="hasHeader" ref="divider" class="m-card__divider" aria-hidden="true" />
    <div class="m-card__body">
      <slot />
    </div>
    <div v-if="slots.footer" class="m-card__footer">
      <slot name="footer" />
    </div>
    <div v-if="slots.seal" class="m-card__seal">
      <slot name="seal" />
    </div>
  </div>
</template>

// packages/react/src/components/card/MCard.tsx
import { useCallback, useEffect, useMemo, type CSSProperties, type ReactNode } from "react";
import {
  cardBrush,
  cardClasses,
  cardDividerLine,
  cardInk,
  createCardDivider,
  ensureCardSheet,
  type CardProps as CoreCardProps,
} from "@shuimo-design/core";
import { useBrushBorder } from "../../ink";
import { useMounted, useSize } from "../../runtime";

export interface MCardProps extends CoreCardProps {
  /** 内容 */
  children?: ReactNode;
  /** 头部（替代 title） */
  header?: ReactNode;
  /** 头部右侧 */
  extra?: ReactNode;
  /** 顶部封面（图片区），裁在边框内 */
  cover?: ReactNode;
  /** 底部 */
  footer?: ReactNode;
  /** 印：盖在卡片右下角，不占内容流，微微探出框外 4px、歪 6°；不传不渲染任何节点 */
  seal?: ReactNode;
  className?: string;
  style?: CSSProperties;
}

export function MCard(props: MCardProps) {
  const { title, seed, padding } = props;
  const hasHeader = Boolean(props.header || props.extra || title);

  const brushRef = useBrushBorder(cardBrush(props));
  const [sizeRef, size] = useSize("border-box");
  const mounted = useMounted();

  // 两个 ref 回调合成一个绑到根元素上
  const ref = useMemo(
    () => (el: HTMLElement | null) => {
      brushRef(el);
      sizeRef(el);
    },
    [brushRef, sizeRef],
  );

  // 纸纹和标题旁的朱批写在 :root 上，所有卡片共用，挂载后生成一次
  useEffect(() => ensureCardSheet(), []);

  const ink = cardInk({ seed, padding, width: size.width, height: size.height, mounted });

  // 头部和内容之间那条线按卡片实际宽度单独生成；控制器只建一次，参数变了重新喂
  const divider = useMemo(() => createCardDivider(seed), []); // eslint-disable-line react-hooks/exhaustive-deps
  const dividerRef = useCallback((el: HTMLElement | null) => divider.attach(el), [divider]);
  useEffect(() => {
    divider.update(cardDividerLine(seed));
  });
  useEffect(() => () => divider.dispose(), [divider]);

  return (
    <div
      ref={ref}
      className={[...cardClasses(props, Boolean(props.cover)), props.className]
        .filter(Boolean)
        .join(" ")}
      style={{ ...ink.style, ...props.style } as CSSProperties}
      {...ink.attrs}
    >
      {props.cover ? <div className="m-card__cover">{props.cover}</div> : null}
      {hasHeader ? (
        <div className="m-card__header">
          <div className="m-card__title">{props.header ?? title}</div>
          {props.extra ? <div className="m-card__extra">{props.extra}</div> : null}
        </div>
      ) : null}
      {hasHeader ? <div ref={dividerRef} className="m-card__divider" aria-hidden="true" /> : null}
      <div className="m-card__body">{props.children}</div>
      {props.footer ? <div className="m-card__footer">{props.footer}</div> : null}
      {props.seal ? <div className="m-card__seal">{props.seal}</div> : null}
    </div>
  );
}
