// packages/vue/src/components/table/MTable.vue
<script setup lang="ts" generic="T extends object">
import { computed, onMounted, ref, useSlots, useTemplateRef } from "vue";
import {
  nextTableSort,
  resolveTableColumns,
  sortTableRows,
  tableCellScope,
  tableCellText,
  tableCellValue,
  tableClasses,
  tableGridTemplate,
  tableHeadScope,
  tableInk,
  tableRowId,
  tableSortAria,
  tableSortClasses,
  tableSortInk,
  tableSortOrder,
  type ResolvedTableColumn,
  type TableEmits,
  type TableSlots,
  type TableSort,
} from "@shuimo-design/core";
import { RenderNode } from "../../runtime/render-node";
import { useSize } from "../../runtime";
import { IconCaretDown, IconCaretUp } from "../../icons";
import { collectColumns, type MTableProps } from "./collect";

defineOptions({ name: "MTable" });

const {
  data = [],
  columns: columnsProp,
  rowKey,
  height,
  align = "center",
  stripe = false,
  emptyText = "暂无数据",
  defaultSort,
  sortRemote = false,
} = defineProps<MTableProps<T>>();
const emit = defineEmits<TableEmits<T>>();
const slots = useSlots() as TableSlots;
defineSlots<TableSlots>();
/** 当前排序；null 是不排。不绑时从 defaultSort 起步 */
const sortModel = defineModel<TableSort | null>("sort");

/**
 * 列的来源：传了 columns 就用传的，没传才从子组件收集。
 * 收集在渲染期完成（读 vnode 的 props），顺序 = 模板里的书写顺序。
 */
const rawColumns = computed(() => columnsProp ?? collectColumns<T>(slots.default?.()));
const columns = computed(() => resolveTableColumns(rawColumns.value, align));
const gridTemplate = computed(() => tableGridTemplate(columns.value));

// ---- 排序：model 没被赋过值（undefined）时用 defaultSort；点表头之后 model 里就是 null 或具体值 ----
const sort = computed(() =>
  sortModel.value === undefined ? (defaultSort ?? null) : sortModel.value,
);
const sortInk = tableSortInk();

function toggleSort(col: ResolvedTableColumn<T>) {
  const next = nextTableSort(sort.value, col.prop);
  sortModel.value = next;
  emit("sortChange", next);
}

/** 排好序的行，key 一并算好；sortRemote 时不在本地排，行序交给服务端 */
const rows = computed(() =>
  sortTableRows(data, sortRemote ? null : sort.value, rawColumns.value).map(({ row, index }) => ({
    row,
    index,
    key: tableRowId(row, index, rowKey),
  })),
);

// ---- 墨线：按表格实际宽度生成，宽度按 32px 分桶 ----
const root = useTemplateRef<HTMLElement>("root");
const { width } = useSize(root, "border-box");
/** 挂载后才敢走素材登记（服务端登记不了），首帧一律内联，两边输出才对得上 */
const mounted = ref(false);
onMounted(() => (mounted.value = true));
const ink = computed(() => tableInk({ width: width.value, mounted: mounted.value }));
</script>

<template>
  <div ref="root" :class="tableClasses({ stripe, height })" :style="ink.style" v-bind="ink.attrs">
    <div class="m-table__scroll" :style="{ maxHeight: height }">
      <table class="m-table__inner" role="table" :style="{ gridTemplateColumns: gridTemplate }">
        <thead class="m-table__head">
          <tr class="m-table__row m-table__row--head" role="row">
            <th
              v-for="col in columns"
              :key="col.key"
              :class="col.headClass"
              role="columnheader"
              scope="col"
              :data-prop="col.prop"
              :aria-sort="col.sortable ? tableSortAria(sort, col.prop) : undefined"
            >
              <!-- 可排序的列：整个表头文字是一个真按钮，键盘也能点；三态循环在 core -->
              <button
                v-if="col.sortable"
                type="button"
                :class="tableSortClasses(tableSortOrder(sort, col.prop))"
                :style="sortInk"
                @click="toggleSort(col)"
              >
                <RenderNode
                  v-if="col.column.renderHead"
                  :node="() => col.column.renderHead!(tableHeadScope(col.column))"
                />
                <template v-else>{{ col.label }}</template>
                <span class="m-table__sort-icons" aria-hidden="true">
                  <span class="m-table__sort-icon m-table__sort-icon--ascending"
                    ><IconCaretUp
                  /></span>
                  <span class="m-table__sort-icon m-table__sort-icon--descending"
                    ><IconCaretDown
                  /></span>
                </span>
              </button>
              <RenderNode
                v-else-if="col.column.renderHead"
                :node="() => col.column.renderHead!(tableHeadScope(col.column))"
              />
              <template v-else>{{ col.label }}</template>
            </th>
          </tr>
        </thead>
        <tbody class="m-table__body">
          <template v-if="rows.length">
            <tr
              v-for="{ row, index, key } in rows"
              :key="key"
              class="m-table__row m-table__row--body"
              role="row"
              @click="emit('rowClick', row, index, $event)"
            >
              <td
                v-for="col in columns"
                :key="col.key"
                :class="col.cellClass"
                role="cell"
                :data-prop="col.prop"
              >
                <RenderNode
                  v-if="col.column.render"
                  :node="() => col.column.render!(tableCellScope(row, index, col.column))"
                />
                <template v-else>{{ tableCellText(tableCellValue(row, col.prop)) }}</template>
              </td>
            </tr>
          </template>
          <tr v-else class="m-table__row m-table__row--empty" role="row">
            <td class="m-table__empty" role="cell" :aria-colspan="columns.length || 1">
              <slot name="empty">{{ emptyText }}</slot>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</template>

// packages/react/src/components/table/MTable.tsx
import {
  Children,
  isValidElement,
  useMemo,
  useState,
  type CSSProperties,
  type MouseEvent,
  type ReactNode,
} from "react";
import {
  nextTableSort,
  resolveTableColumns,
  sortTableRows,
  tableCellScope,
  tableCellText,
  tableCellValue,
  tableClasses,
  tableGridTemplate,
  tableHeadScope,
  tableInk,
  tableRowId,
  tableSortAria,
  tableSortClasses,
  tableSortInk,
  tableSortOrder,
  type TableColumnConfig,
  type TableProps as CoreTableProps,
  type TableRow,
  type TableSort,
} from "@shuimo-design/core";
import { IconCaretDown, IconCaretUp } from "../../icons";
import { useMounted, useSize } from "../../runtime";
import { MTableColumn, type MTableColumnProps } from "./MTableColumn";

/** React 这边的一列：render / renderHead 返回 ReactNode */
export type ReactTableColumn<Row = TableRow> = TableColumnConfig<Row, ReactNode>;

export interface MTableProps<Row extends object = TableRow> extends Omit<
  CoreTableProps<Row>,
  "columns"
> {
  /** 列声明，顺序就是列序；不传则按书写顺序从子组件 MTableColumn 上收集 */
  columns?: ReactTableColumn<Row>[];
  /** 受控的排序，null 是不排；不传就由组件自己记（配合 defaultSort） */
  sort?: TableSort | null;
  /** 排序变化；null 是取消排序 */
  onSortChange?: (sort: TableSort | null) => void;
  /** 点击某一行 */
  onRowClick?: (row: Row, index: number, event: MouseEvent) => void;
  /** 没有数据时显示的内容，优先于 emptyText */
  empty?: ReactNode;
  /** 放 MTableColumn（语法糖；传了 columns 就不看这里） */
  children?: ReactNode;
  className?: string;
  style?: CSSProperties;
}

/**
 * 从 children 里按**书写顺序**收集 MTableColumn 的配置。
 *
 * 全程在渲染期完成：读的是元素上的 props。effect 的执行顺序在 Fragment / Suspense /
 * 并发切片下不保证跟 DOM 一致，服务端更是没有 DOM —— 所以列序不能靠子组件登记。
 */
function collectColumns<Row>(children: ReactNode): ReactTableColumn<Row>[] {
  const columns: ReactTableColumn<Row>[] = [];
  for (const node of Children.toArray(children)) {
    if (!isValidElement(node) || node.type !== MTableColumn) continue;
    const props = node.props as MTableColumnProps<Row>;
    columns.push({
      prop: props.prop,
      label: props.label,
      width: props.width,
      align: props.align,
      sortable: props.sortable,
      render: props.render,
      renderHead: props.renderHead,
    });
  }
  return columns;
}

export function MTable<Row extends object = TableRow>(props: MTableProps<Row>) {
  const {
    data = [],
    rowKey,
    height,
    align = "center",
    stripe = false,
    emptyText = "暂无数据",
    empty,
    children,
    sortRemote = false,
  } = props;

  // 列的来源：传了 columns 就用传的，没传才从 children 收集
  const rawColumns = props.columns ?? collectColumns<Row>(children);
  const columns = resolveTableColumns(rawColumns, align);

  /* ---------- 排序：受控 / 非受控都支持 ---------- */
  const sortControlled = props.sort !== undefined;
  const [ownSort, setOwnSort] = useState<TableSort | null>(props.defaultSort ?? null);
  const sort = sortControlled ? props.sort! : ownSort;
  const sortInk = tableSortInk();

  function toggleSort(prop: string) {
    const next = nextTableSort(sort, prop);
    if (!sortControlled) setOwnSort(next);
    props.onSortChange?.(next);
  }

  /** 排好序的行，key 一并算好；sortRemote 时不在本地排，行序交给服务端 */
  const localSort = sortRemote ? null : sort;
  const rows = useMemo(
    () =>
      sortTableRows(data, localSort, rawColumns).map(({ row, index }) => ({
        row,
        index,
        key: tableRowId(row, index, rowKey),
      })),
    [data, localSort, rawColumns, rowKey],
  );

  // ---- 墨线：按表格实际宽度生成，宽度按 32px 分桶。首帧量到 0，渲染朴素版 ----
  const [rootRef, size] = useSize();
  const mounted = useMounted();
  const ink = tableInk({ width: size.width, mounted });

  return (
    <div
      ref={rootRef}
      className={[...tableClasses({ stripe, height }), props.className].filter(Boolean).join(" ")}
      style={{ ...ink.style, ...props.style } as CSSProperties}
      {...ink.attrs}
    >
      <div className="m-table__scroll" style={{ maxHeight: height }}>
        <table
          className="m-table__inner"
          role="table"
          style={{ gridTemplateColumns: tableGridTemplate(columns) }}
        >
          <thead className="m-table__head">
            <tr className="m-table__row m-table__row--head" role="row">
              {columns.map((col) => {
                const head = col.column.renderHead
                  ? col.column.renderHead(tableHeadScope(col.column))
                  : col.label;
                return (
                  <th
                    key={col.key}
                    className={col.headClass}
                    role="columnheader"
                    scope="col"
                    data-prop={col.prop}
                    aria-sort={col.sortable ? tableSortAria(sort, col.prop) : undefined}
                  >
                    {/* 可排序的列：整个表头文字是一个真按钮，键盘也能点；三态循环在 core */}
                    {col.sortable ? (
                      <button
                        type="button"
                        className={tableSortClasses(tableSortOrder(sort, col.prop)).join(" ")}
                        style={sortInk as CSSProperties}
                        onClick={() => toggleSort(col.prop)}
                      >
                        {head}
                        <span className="m-table__sort-icons" aria-hidden="true">
                          <span className="m-table__sort-icon m-table__sort-icon--ascending">
                            <IconCaretUp />
                          </span>
                          <span className="m-table__sort-icon m-table__sort-icon--descending">
                            <IconCaretDown />
                          </span>
                        </span>
                      </button>
                    ) : (
                      head
                    )}
                  </th>
                );
              })}
            </tr>
          </thead>
          <tbody className="m-table__body">
            {rows.length > 0 ? (
              rows.map(({ row, index, key }) => (
                <tr
                  key={key}
                  className="m-table__row m-table__row--body"
                  role="row"
                  onClick={(event) => props.onRowClick?.(row, index, event)}
                >
                  {columns.map((col) => (
                    <td key={col.key} className={col.cellClass} role="cell" data-prop={col.prop}>
                      {col.column.render
                        ? col.column.render(tableCellScope(row, index, col.column))
                        : tableCellText(tableCellValue(row, col.prop))}
                    </td>
                  ))}
                </tr>
              ))
            ) : (
              <tr className="m-table__row m-table__row--empty" role="row">
                <td className="m-table__empty" role="cell" aria-colspan={columns.length || 1}>
                  {empty ?? emptyText}
                </td>
              </tr>
            )}
          </tbody>
        </table>
      </div>
    </div>
  );
}
