// playground/src/react/App.tsx
import { Fragment, useEffect, useRef, useState, type ComponentType } from "react";
import { flushSync } from "react-dom";
import { MButton, MList, MListItem, MOverlayOutlet, MRicePaper } from "@shuimo-design/react";
import { startInkViewTransition } from "@shuimo-design/core/ink";
import ApiDoc from "./ApiDoc";
import { ALL_DEMOS, CATALOG, assertComplete, fileOf, readHash } from "../shared/catalog";

/**
 * React 版文档站的外壳。Vue 版（src/vue/App.vue）是同一套结构、同一份样式、同一份清单，
 * 只是用 Vue 写的 —— 两边各自独立成站，谁都不寄生在对方的应用里。
 */

// 按清单把 demos/ 下的示例对上号；少一个就直接炸，不要静默少一页
const modules = import.meta.glob<ComponentType>("./demos/*Demo.tsx", {
  eager: true,
  import: "default",
});
const demos: Record<string, ComponentType> = {};
for (const meta of ALL_DEMOS) {
  const found = modules[`./demos/${fileOf(meta.id)}.tsx`];
  if (found) demos[meta.id] = found;
}
assertComplete(demos, "demos", ".tsx");

export default function App() {
  const [dark, setDark] = useState(false);
  const [seed, setSeed] = useState(42);
  const [currentId, setCurrentId] = useState(readHash);

  const current = ALL_DEMOS.find((d) => d.id === currentId) ?? ALL_DEMOS[0]!;
  const Demo = demos[current.id]!;

  // 左右两栏各自滚动
  const main = useRef<HTMLElement>(null);
  const nav = useRef<HTMLElement>(null);

  useEffect(() => {
    const onHashChange = () => setCurrentId(readHash());
    window.addEventListener("hashchange", onHashChange);
    return () => window.removeEventListener("hashchange", onHashChange);
  }, []);

  // 切页时右栏拉回顶部；左栏把当前项滚进可视区（直接带 hash 打开时也能看到选中项）
  useEffect(() => {
    main.current?.scrollTo({ top: 0 });
    nav.current?.querySelector(".pg__item--active")?.scrollIntoView({ block: "nearest" });
  }, [currentId]);

  function go(id: string) {
    if (id === currentId) return;
    location.hash = `#/${id}`;
  }

  function toggleDark() {
    const next = !dark;
    setDark(next);
    document.documentElement.dataset.theme = next ? "dark" : "light";
  }

  function nextPaperWithTransition() {
    // flushSync 不能省：转场要在回调里拍到"换完之后"的 DOM，而 React 的 setState 默认不是同步落地的
    void startInkViewTransition(() => {
      flushSync(() => setSeed((n) => n + 1));
    });
  }

  return (
    <MRicePaper seed={seed} goldFlecks style={{ height: "100vh" }}>
      <div className="pg">
        <aside className="pg__aside">
          <h1 className="pg__logo">
            水墨 <span>next</span>
          </h1>
          <p className="pg__flavor">
            <span className="pg__flavor-cur">React</span>
            <a className="pg__flavor-alt" href={`../vue/#/${currentId}`}>
              看 Vue 版 →
            </a>
          </p>
          <nav ref={nav} className="pg__nav">
            {CATALOG.map((group) => (
              <Fragment key={group.group}>
                <p className="pg__group">{group.group}</p>
                <MList marker={false}>
                  {group.items.map((item) => (
                    <MListItem
                      key={item.id}
                      active={item.id === currentId}
                      className={item.id === currentId ? "pg__item pg__item--active" : "pg__item"}
                      onClick={() => go(item.id)}
                    >
                      {item.title}
                      <span className="pg__item-name">{item.name}</span>
                    </MListItem>
                  ))}
                </MList>
              </Fragment>
            ))}
          </nav>
          <div className="pg__tools">
            <MButton onClick={toggleDark}>{dark ? "转亮" : "转暗"}</MButton>
            <MButton onClick={nextPaperWithTransition}>换纸</MButton>
          </div>
        </aside>

        <main ref={main} className="pg__main">
          {/* 切换不做转场，直接换页；落墨转场只在 MInkTransition 自己的示例页里演示 */}
          <section key={current.id} className="pg__page">
            <header className="pg__header">
              <h2 className="pg__title">{current.title}</h2>
              <code className="pg__code">{current.name}</code>
            </header>
            <Demo />
            {/* 示例底下挂上构建时生成的属性 / 事件 / 内容表（docs/api/<组件名>.json） */}
            <ApiDoc name={current.name} />
          </section>
        </main>
      </div>
      {/* 函数式的消息 / 确认框渲染在自己的树里，要有这个出口才弹得出来（MConfigProvider 自带一个） */}
      <MOverlayOutlet />
    </MRicePaper>
  );
}

// playground/src/App.vue
<script setup lang="ts">
import { computed, nextTick, onBeforeUnmount, onMounted, ref, useTemplateRef, watch } from "vue";
import { MButton, MList, MListItem, MRicePaper } from "@shuimo-design/vue";
import { startInkViewTransition } from "@shuimo-design/core/ink";
import ApiDoc from "./ApiDoc.vue";
import { ALL_DEMOS, DEMOS } from "./registry";

const dark = ref(false);
const seed = ref(42);

function readHash(): string {
  return location.hash.replace(/^#\/?/, "") || ALL_DEMOS[0]!.id;
}
const currentId = ref(readHash());
const current = computed(() => ALL_DEMOS.find((d) => d.id === currentId.value) ?? ALL_DEMOS[0]!);

// 左右两栏各自滚动，切页时只把右栏拉回顶部；左栏把当前项滚进可视区（直接带 hash 打开时也能看到选中项）
const main = useTemplateRef<HTMLElement>("main");
const nav = useTemplateRef<HTMLElement>("nav");

function onHashChange() {
  currentId.value = readHash();
}
function go(id: string) {
  if (id === currentId.value) return;
  location.hash = `#/${id}`;
}

function revealActive() {
  nav.value?.querySelector(".pg__item--active")?.scrollIntoView({ block: "nearest" });
}

watch(currentId, () => {
  main.value?.scrollTo({ top: 0 });
  void nextTick(revealActive);
});

onMounted(() => {
  window.addEventListener("hashchange", onHashChange);
  revealActive();
});
onBeforeUnmount(() => window.removeEventListener("hashchange", onHashChange));

function toggleDark() {
  dark.value = !dark.value;
  document.documentElement.dataset.theme = dark.value ? "dark" : "light";
}

function nextPaperWithTransition() {
  void startInkViewTransition(() => {
    seed.value++;
  });
}
</script>

<template>
  <MRicePaper :seed="seed" gold-flecks style="height: 100vh">
    <div class="pg">
      <aside class="pg__aside">
        <h1 class="pg__logo">水墨 <span>next</span></h1>
        <nav ref="nav" class="pg__nav">
          <template v-for="group in DEMOS" :key="group.group">
            <p class="pg__group">{{ group.group }}</p>
            <MList :marker="false">
              <MListItem
                v-for="item in group.items"
                :key="item.id"
                :active="item.id === currentId"
                class="pg__item"
                :class="{ 'pg__item--active': item.id === currentId }"
                @click="go(item.id)"
              >
                {{ item.title }}
                <span class="pg__item-name">{{ item.name }}</span>
              </MListItem>
            </MList>
          </template>
        </nav>
        <div class="pg__tools">
          <MButton @click="toggleDark">{{ dark ? "转亮" : "转暗" }}</MButton>
          <MButton @click="nextPaperWithTransition">换纸</MButton>
        </div>
      </aside>

      <main ref="main" class="pg__main">
        <!-- 切换不做转场，直接换页；落墨转场只在 MInkTransition 自己的示例页里演示 -->
        <section :key="current.id" class="pg__page">
          <header class="pg__header">
            <h2 class="pg__title">{{ current.title }}</h2>
            <code class="pg__code">{{ current.name }}</code>
          </header>
          <component :is="current.component" />
          <!-- 示例底下挂上构建时生成的属性 / 事件 / 插槽表（docs/api/<组件名>.json） -->
          <ApiDoc :name="current.name" />
        </section>
      </main>
    </div>
  </MRicePaper>
</template>

<style scoped>
/* 整页定高、外层不滚，左右两栏各自竖向滚动；宣纸和远山留在底下当固定背景 */
.pg {
  display: grid;
  grid-template-columns: 220px minmax(0, 1fr);
  height: 100vh;
}
.pg__aside {
  display: flex;
  flex-direction: column;
  box-sizing: border-box;
  height: 100vh;
  padding: 24px 16px;
  border-right: 1px solid var(--m-divider);
  overflow-y: auto;
  overscroll-behavior: contain;
}
.pg__logo {
  margin: 0 8px 20px;
  font-family: var(--m-font-brush);
  font-size: 24px;
  font-weight: 400;
  letter-spacing: 0.1em;
}
.pg__logo span {
  font-family: var(--m-font-sans);
  font-size: 12px;
  color: var(--m-fg-muted);
  letter-spacing: 0.2em;
  vertical-align: middle;
}
.pg__nav {
  flex: 1;
}
.pg__group {
  margin: 12px 8px 4px;
  font-size: 12px;
  color: var(--m-fg-muted);
  letter-spacing: 0.2em;
}
.pg__item {
  display: flex;
  align-items: baseline;
  justify-content: space-between;
  gap: 8px;
  padding: 6px 8px;
  border-radius: var(--m-radius);
  cursor: var(--m-cursor-pointer);
  transition: background-color var(--m-duration) var(--m-ease);
}
.pg__item:hover {
  background: color-mix(in srgb, var(--m-ink) 6%, transparent);
}
/* 当前页：淡墨底 + 左侧一道朱砂，正文加重 */
.pg__item--active,
.pg__item--active:hover {
  background: color-mix(in srgb, var(--m-ink) 10%, transparent);
  box-shadow: inset 3px 0 0 var(--m-seal);
  color: var(--m-fg-strong);
  font-weight: 500;
}
.pg__item-name {
  font-size: 11px;
  color: var(--m-fg-muted);
  opacity: 0.7;
}
.pg__tools {
  display: flex;
  gap: 8px;
  padding-top: 16px;
}
.pg__main {
  box-sizing: border-box;
  height: 100vh;
  padding: 32px 40px;
  min-width: 0;
  overflow-y: auto;
  overscroll-behavior: contain;
}
.pg__page {
  max-width: 880px;
}
.pg__header {
  display: flex;
  align-items: baseline;
  gap: 12px;
  margin-bottom: 24px;
}
.pg__title {
  margin: 0;
  font-size: 24px;
  font-weight: 500;
}
.pg__code {
  font-size: 13px;
  color: var(--m-fg-muted);
}
</style>
