// packages/ui/src/components/breadcrumb/MBreadcrumbItem.vue
<script setup lang="ts">
import "./breadcrumb.css";
import { computed, inject } from "vue";
import { breadcrumbKey } from "./context";
import type { BreadcrumbItemProps, BreadcrumbItemSlots } from "./types";

defineOptions({ name: "MBreadcrumbItem" });

const { content, href } = defineProps<BreadcrumbItemProps>();
defineSlots<BreadcrumbItemSlots>();

const breadcrumb = inject(breadcrumbKey, undefined);
const separatorText = computed(() => breadcrumb?.separator.value);
// 父组件的 separator 插槽当函数式组件渲染，每一项各画一份
const SeparatorSlot = computed(() => breadcrumb?.separatorSlot());
</script>

<template>
  <li class="m-breadcrumb-item">
    <span class="m-breadcrumb-item__separator" aria-hidden="true">
      <component :is="SeparatorSlot" v-if="SeparatorSlot" />
      <template v-else-if="separatorText">{{ separatorText }}</template>
      <i v-else class="m-breadcrumb-item__slash" />
    </span>
    <a v-if="href" class="m-breadcrumb-item__content" :href="href"
      ><slot>{{ content }}</slot></a
    >
    <span v-else class="m-breadcrumb-item__content"
      ><slot>{{ content }}</slot></span
    >
  </li>
</template>

// packages/react/src/components/breadcrumb/MBreadcrumbItem.tsx
import { useContext, type CSSProperties, type ReactNode } from "react";
import {
  breadcrumbSeparatorKind,
  type BreadcrumbItemProps as CoreBreadcrumbItemProps,
} from "@shuimo-design/core";
import { BreadcrumbContext } from "./context";

export interface MBreadcrumbItemProps extends CoreBreadcrumbItemProps {
  /** 项内容，替代 content */
  children?: ReactNode;
  className?: string;
  style?: CSSProperties;
}

export function MBreadcrumbItem(props: MBreadcrumbItemProps) {
  const { content, href, children } = props;
  const breadcrumb = useContext(BreadcrumbContext);
  // 画哪种分隔符的判断在 core，两个壳才不会各判一套
  const kind = breadcrumbSeparatorKind({
    custom: Boolean(breadcrumb?.separatorNode),
    context: breadcrumb,
  });
  const body = children ?? content;

  return (
    <li
      className={["m-breadcrumb-item", props.className].filter(Boolean).join(" ")}
      style={props.style}
    >
      <span className="m-breadcrumb-item__separator" aria-hidden="true">
        {kind === "custom" ? breadcrumb?.separatorNode : null}
        {kind === "text" ? breadcrumb?.separator : null}
        {kind === "slash" ? <i className="m-breadcrumb-item__slash" /> : null}
      </span>
      {href ? (
        <a className="m-breadcrumb-item__content" href={href}>
          {body}
        </a>
      ) : (
        <span className="m-breadcrumb-item__content">{body}</span>
      )}
    </li>
  );
}
