// packages/ui/src/components/input-number/MInputNumber.vue
<script setup lang="ts">
import "./input-number.css";
import { computed, ref, useAttrs, useTemplateRef, watch } from "vue";
import { IconMinus, IconPlus } from "../../icons";
import { brushLineUrl } from "../../ink/assets/line";
import { inkMarkUrl } from "../../ink/assets/mark";
import { FIELD_STROKE } from "../../internal/field-stroke";
import { useDisabled, useFormItem } from "../../internal/form-item";
import { useBrushBorder } from "../../ink/stroke";
import type { InputNumberEmits, InputNumberProps } from "./types";

defineOptions({ name: "MInputNumber", inheritAttrs: false });

const {
  min = -Infinity,
  max = Infinity,
  step = 1,
  precision,
  disabled: disabledProp = false,
  readonly = false,
  placeholder,
  controls = true,
  name,
} = defineProps<InputNumberProps>();
const emit = defineEmits<InputNumberEmits>();
const model = defineModel<number | undefined>();

const attrs = useAttrs();
/** class/style 落在外层，其余原生属性交给 input */
const nativeAttrs = computed(() => {
  const { class: _c, style: _s, ...rest } = attrs;
  return rest;
});
const formItem = useFormItem();
const disabled = useDisabled(() => disabledProp);
const focused = ref(false);
const native = useTemplateRef<HTMLInputElement>("native");
const root = useTemplateRef<HTMLElement>("root");
// 外框和输入框共用同一套细笔触参数，两者并排时边框粗细一致
useBrushBorder(root, FIELD_STROKE);
// 水墨皮肤下，加减号换成素材库里一笔写出的记号，按钮与输入区之间隔一道按控件高度生成的短竖笔
const divider = brushLineUrl({ seed: 7, length: 36, thickness: 1.2, vertical: true });
const inkStyle = {
  "--m-input-number-plus": `url("${inkMarkUrl("plus", { seed: 4, strokeWidth: 2.2 })}")`,
  "--m-input-number-minus": `url("${inkMarkUrl("minus", { seed: 4, strokeWidth: 2.2 })}")`,
  "--m-input-number-divider": `url("${divider.url}")`,
  "--m-input-number-divider-band": `${divider.width}px`,
};

/** 小数点后有几位；用来把浮点加减的结果修回来（0.1 + 0.2） */
function decimalsOf(value: number): number {
  if (!Number.isFinite(value)) return 0;
  const text = String(value);
  const dot = text.indexOf(".");
  return dot < 0 ? 0 : text.length - dot - 1;
}

/** 钳制到 min/max 并按 precision 取整 */
function normalize(value: number): number {
  const clamped = Math.min(max, Math.max(min, value));
  return precision === undefined ? clamped : Number(clamped.toFixed(precision));
}

function format(value: number | undefined): string {
  if (value === undefined) return "";
  return precision === undefined ? String(value) : value.toFixed(precision);
}

/** 显示的文本；输入过程中允许 `-`、`1.` 这类中间态 */
const text = ref(format(model.value));
watch(model, (value) => {
  text.value = format(value);
});

/** 键入时的清洗：只留数字 / 一个前置 `-` / 一个 `.`；`.` 开头补 `0.`；去前导 0；按 precision 截断 */
function sanitize(raw: string): string {
  let out = "";
  let dotted = false;
  for (const ch of raw) {
    if (ch >= "0" && ch <= "9") out += ch;
    else if (ch === "-" && out === "") out += ch;
    else if (ch === "." && !dotted && precision !== 0) {
      dotted = true;
      out += ch;
    }
  }
  out = out.replace(/^(-?)\./, "$10.");
  out = out.replace(/^(-?)0+(?=\d)/, "$1");
  if (precision !== undefined) {
    const dot = out.indexOf(".");
    if (dot >= 0) out = out.slice(0, dot + 1 + precision);
  }
  return out;
}

/** 把文本解析成数：空串是 undefined，解析不了是 NaN */
function parse(raw: string): number | undefined {
  let s = raw.endsWith(".") ? raw.slice(0, -1) : raw;
  if (s === "-") s = "";
  if (s === "") return undefined;
  const n = Number(s);
  return Number.isFinite(n) ? normalize(n) : Number.NaN;
}

function write(next: number | undefined) {
  const old = model.value;
  text.value = format(next);
  if (next !== old) {
    model.value = next;
    emit("change", next, old);
  }
  formItem?.validate("change");
}

/** 提交：清洗文本写回 model，非法则回退到旧值 */
function commit() {
  const parsed = parse(text.value);
  if (parsed !== undefined && Number.isNaN(parsed)) {
    text.value = format(model.value);
    return;
  }
  write(parsed);
}

function stepBy(direction: 1 | -1) {
  if (disabled.value || readonly) return;
  const typed = parse(text.value);
  const base = typed === undefined || Number.isNaN(typed) ? (model.value ?? normalize(0)) : typed;
  const digits = Math.max(decimalsOf(base), decimalsOf(step));
  write(normalize(Number((base + direction * step).toFixed(digits))));
}

const decreaseDisabled = computed(
  () => disabled.value || readonly || (model.value !== undefined && model.value <= min),
);
const increaseDisabled = computed(
  () => disabled.value || readonly || (model.value !== undefined && model.value >= max),
);
const ariaMin = computed(() => (Number.isFinite(min) ? min : undefined));
const ariaMax = computed(() => (Number.isFinite(max) ? max : undefined));

function onInput(event: Event) {
  const el = event.target as HTMLInputElement;
  const next = sanitize(el.value);
  if (el.value !== next) el.value = next;
  text.value = next;
  emit("input", next);
}

function onKeydown(event: KeyboardEvent) {
  if (event.key === "ArrowUp" || event.key === "ArrowDown") {
    event.preventDefault();
    stepBy(event.key === "ArrowUp" ? 1 : -1);
  } else if (event.key === "Enter") {
    commit();
  }
}

function onFocus(event: FocusEvent) {
  focused.value = true;
  emit("focus", event);
}

function onBlur(event: FocusEvent) {
  focused.value = false;
  commit();
  emit("blur", event);
  formItem?.validate("blur");
}

function focus() {
  native.value?.focus();
}
function blur() {
  native.value?.blur();
}
function select() {
  native.value?.select();
}

defineExpose({ focus, blur, select });
</script>

<template>
  <div
    ref="root"
    class="m-input-number"
    :class="[
      {
        'm-input-number--disabled': disabled,
        'm-input-number--readonly': readonly,
        'm-input-number--focused': focused,
        'm-input-number--controls': controls,
      },
      $attrs.class,
    ]"
    :style="[$attrs.style as string | undefined, inkStyle]"
  >
    <button
      v-if="controls"
      type="button"
      class="m-input-number__decrease"
      aria-label="减少"
      tabindex="-1"
      :disabled="decreaseDisabled"
      @mousedown.prevent
      @click="stepBy(-1)"
    >
      <IconMinus class="m-input-number__icon" />
      <span class="m-input-number__glyph m-input-number__glyph--minus" aria-hidden="true" />
    </button>
    <input
      v-bind="nativeAttrs"
      :id="formItem?.id.value"
      ref="native"
      class="m-input-number__native"
      type="text"
      role="spinbutton"
      inputmode="decimal"
      autocomplete="off"
      :value="text"
      :placeholder="placeholder"
      :disabled="disabled"
      :readonly="readonly"
      :name="name"
      :aria-valuenow="model"
      :aria-valuemin="ariaMin"
      :aria-valuemax="ariaMax"
      @input="onInput"
      @keydown="onKeydown"
      @focus="onFocus"
      @blur="onBlur"
    />
    <button
      v-if="controls"
      type="button"
      class="m-input-number__increase"
      aria-label="增加"
      tabindex="-1"
      :disabled="increaseDisabled"
      @mousedown.prevent
      @click="stepBy(1)"
    >
      <IconPlus class="m-input-number__icon" />
      <span class="m-input-number__glyph m-input-number__glyph--plus" aria-hidden="true" />
    </button>
  </div>
</template>

// packages/react/src/components/input-number/MInputNumber.tsx
import {
  forwardRef,
  useImperativeHandle,
  useRef,
  useState,
  type CSSProperties,
  type ChangeEvent,
  type ComponentPropsWithoutRef,
  type FocusEvent,
  type KeyboardEvent,
} from "react";
import {
  formatNumber,
  inputNumberAriaBound,
  inputNumberBrush,
  inputNumberClasses,
  inputNumberInk,
  inputNumberStepDisabled,
  parseNumberText,
  sanitizeNumberText,
  stepNumber,
  INPUT_NUMBER_DECREASE_LABEL,
  INPUT_NUMBER_INCREASE_LABEL,
  type InputNumberExpose,
  type InputNumberProps as CoreInputNumberProps,
} from "@shuimo-design/core";
import { IconMinus, IconPlus } from "../../icons";
import { useBrushBorder } from "../../ink";
import { useDisabled, useFormItem } from "../../internal/form-item";

/** 没被组件用掉的属性原样落到原生 input 上，对应 Vue 那边的 inheritAttrs: false */
type NativeAttrs = Omit<
  ComponentPropsWithoutRef<"input">,
  | "className"
  | "defaultValue"
  | "disabled"
  | "max"
  | "min"
  | "name"
  | "onBlur"
  | "onChange"
  | "onFocus"
  | "onInput"
  | "onKeyDown"
  | "placeholder"
  | "readOnly"
  | "step"
  | "style"
  | "type"
  | "value"
>;

export interface MInputNumberProps extends CoreInputNumberProps, NativeAttrs {
  /** 受控值；不传就由组件自己记（配合 defaultValue） */
  value?: number;
  defaultValue?: number;
  onValueChange?: (value: number | undefined) => void;
  /** 值提交后（失焦、回车、按钮或方向键增减），参数是新值与旧值 */
  onChange?: (value: number | undefined, oldValue: number | undefined) => void;
  /** 每次键入，参数是清洗后的文本（可能是 `-`、`1.` 这类中间态） */
  onInput?: (value: string) => void;
  onFocus?: (event: FocusEvent<HTMLInputElement>) => void;
  onBlur?: (event: FocusEvent<HTMLInputElement>) => void;
  onKeyDown?: (event: KeyboardEvent<HTMLInputElement>) => void;
  className?: string;
  style?: CSSProperties;
}

export const MInputNumber = forwardRef<InputNumberExpose, MInputNumberProps>(
  function MInputNumber(props, ref) {
    const {
      min = -Infinity,
      max = Infinity,
      step = 1,
      precision,
      disabled: disabledProp = false,
      readonly = false,
      placeholder,
      controls = true,
      name,
      value,
      defaultValue,
      onValueChange,
      onChange,
      onInput,
      onFocus,
      onBlur,
      onKeyDown,
      className,
      style,
      ...nativeAttrs
    } = props;

    // 上下文形状在 core（context/form-item.ts），这两行只是 React 的 useContext 胶水
    const formItem = useFormItem();
    const disabled = useDisabled(disabledProp);

    // 受控 / 非受控两种都支持。这里用"有没有传这个 prop"判断，不能用 value !== undefined：
    // 数字框的空值本来就是 undefined，受控的父组件清空时传的正是 undefined
    const isControlled = "value" in props;
    const [uncontrolled, setUncontrolled] = useState<number | undefined>(defaultValue);
    const model = isControlled ? value : uncontrolled;

    const [focused, setFocused] = useState(false);
    const native = useRef<HTMLInputElement>(null);
    // 外框和输入框共用同一套细笔触参数，两者并排时边框粗细一致
    const root = useBrushBorder(inputNumberBrush());
    // 加减号和中间那道短竖笔都在 core 里生成，两个壳共用同一份遮罩
    const inkStyle = inputNumberInk();

    /** 所有算术（钳制、取整、清洗、解析、步进）都在 core，这里只传边界 */
    const bounds = { min, max, precision };

    /** 显示的文本；输入过程中允许 `-`、`1.` 这类中间态 */
    const [text, setText] = useState(() => formatNumber(model, precision));
    // 绑定值从外面变了就重排文本。对应 Vue 的 watch(model)，
    // React 里"由 props 推导 state"的正规写法就是渲染期比一次上一轮的值
    const [prevModel, setPrevModel] = useState(model);
    if (prevModel !== model) {
      setPrevModel(model);
      setText(formatNumber(model, precision));
    }

    function write(next: number | undefined) {
      const old = model;
      setText(formatNumber(next, precision));
      if (next !== old) {
        if (!isControlled) setUncontrolled(next);
        onValueChange?.(next);
        onChange?.(next, old);
      }
      formItem.validate("change");
    }

    /** 提交：清洗文本写回绑定值，非法则回退到旧值 */
    function commit() {
      const parsed = parseNumberText(text, bounds);
      if (parsed !== undefined && Number.isNaN(parsed)) {
        setText(formatNumber(model, precision));
        return;
      }
      write(parsed);
    }

    function stepBy(direction: 1 | -1) {
      if (disabled || readonly) return;
      write(stepNumber({ text, value: model, step, direction, bounds }));
    }

    function handleInput(event: ChangeEvent<HTMLInputElement>) {
      const el = event.currentTarget;
      const next = sanitizeNumberText(el.value, precision);
      // 清洗后和上一轮同值时 React 不会重渲染，得自己把输入框里的非法字符抹掉
      if (el.value !== next) el.value = next;
      setText(next);
      onInput?.(next);
    }

    function handleKeyDown(event: KeyboardEvent<HTMLInputElement>) {
      onKeyDown?.(event);
      if (event.key === "ArrowUp" || event.key === "ArrowDown") {
        event.preventDefault();
        stepBy(event.key === "ArrowUp" ? 1 : -1);
      } else if (event.key === "Enter") {
        commit();
      }
    }

    function handleFocus(event: FocusEvent<HTMLInputElement>) {
      setFocused(true);
      onFocus?.(event);
    }

    function handleBlur(event: FocusEvent<HTMLInputElement>) {
      setFocused(false);
      commit();
      onBlur?.(event);
      formItem.validate("blur");
    }

    // 和 Vue 的 defineExpose({ focus, blur, select }) 对齐
    useImperativeHandle(
      ref,
      () => ({
        focus: () => native.current?.focus(),
        blur: () => native.current?.blur(),
        select: () => native.current?.select(),
      }),
      [],
    );

    const classes = inputNumberClasses({ disabled, readonly, focused, controls });

    return (
      <div
        ref={root}
        className={[...classes, className].filter(Boolean).join(" ")}
        style={{ ...inkStyle, ...style } as CSSProperties}
      >
        {controls ? (
          <button
            type="button"
            className="m-input-number__decrease"
            aria-label={INPUT_NUMBER_DECREASE_LABEL}
            tabIndex={-1}
            disabled={inputNumberStepDisabled({
              direction: -1,
              value: model,
              disabled,
              readonly,
              min,
              max,
            })}
            onMouseDown={(event) => event.preventDefault()}
            onClick={() => stepBy(-1)}
          >
            <IconMinus className="m-input-number__icon" />
            <span
              className="m-input-number__glyph m-input-number__glyph--minus"
              aria-hidden="true"
            />
          </button>
        ) : null}
        <input
          {...nativeAttrs}
          ref={native}
          id={formItem.id}
          className="m-input-number__native"
          type="text"
          role="spinbutton"
          inputMode="decimal"
          autoComplete="off"
          value={text}
          placeholder={placeholder}
          disabled={disabled}
          readOnly={readonly}
          name={name}
          aria-valuenow={model}
          aria-valuemin={inputNumberAriaBound(min)}
          aria-valuemax={inputNumberAriaBound(max)}
          onChange={handleInput}
          onKeyDown={handleKeyDown}
          onFocus={handleFocus}
          onBlur={handleBlur}
        />
        {controls ? (
          <button
            type="button"
            className="m-input-number__increase"
            aria-label={INPUT_NUMBER_INCREASE_LABEL}
            tabIndex={-1}
            disabled={inputNumberStepDisabled({
              direction: 1,
              value: model,
              disabled,
              readonly,
              min,
              max,
            })}
            onMouseDown={(event) => event.preventDefault()}
            onClick={() => stepBy(1)}
          >
            <IconPlus className="m-input-number__icon" />
            <span
              className="m-input-number__glyph m-input-number__glyph--plus"
              aria-hidden="true"
            />
          </button>
        ) : null}
      </div>
    );
  },
);
