// playground/src/demos-react/SwitchDemo.tsx
import { useState } from "react";
import { MSwitch, type SwitchValue } from "@shuimo-design/react";

export default function SwitchDemo() {
  const [basic, setBasic] = useState<SwitchValue>(false);
  const [withText, setWithText] = useState<SwitchValue>(true);
  const [withSlot, setWithSlot] = useState<SwitchValue>(true);
  const [loading, setLoading] = useState<SwitchValue>(false);
  const [disabled, setDisabled] = useState<SwitchValue>(false);
  const [changed, setChanged] = useState<SwitchValue>(false);
  const [lastChange, setLastChange] = useState<SwitchValue>();
  const [controlled, setControlled] = useState<SwitchValue>(false);
  const [asked, setAsked] = useState<SwitchValue>();
  const [mode, setMode] = useState<SwitchValue>("day");

  function onControlledChange(next: SwitchValue) {
    // 受控：组件不自己改值，这里模拟"问过之后才切"
    setAsked(next);
    window.setTimeout(() => setControlled(next === true), 600);
  }

  return (
    <div className="demo">
      <div className="demo__block">
        <p className="demo__caption">普通开关</p>
        <div className="demo__row">
          <span>参数值为：{String(basic)}</span>
          <MSwitch value={basic} onValueChange={setBasic} />
        </div>
      </div>

      <div className="demo__block">
        <p className="demo__caption">activeText / inactiveText</p>
        <div className="demo__row">
          <MSwitch
            value={withText}
            onValueChange={setWithText}
            activeText="active"
            inactiveText="inactive"
          />
        </div>
      </div>

      <div className="demo__block">
        <p className="demo__caption">active / inactive 节点覆盖文字</p>
        <div className="demo__row">
          <MSwitch
            value={withSlot}
            onValueChange={setWithSlot}
            activeText="active"
            inactiveText="inactive"
            active={<span>这里是 active slot</span>}
          />
        </div>
      </div>

      <div className="demo__block">
        <p className="demo__caption">loading / disabled</p>
        <div className="demo__row">
          <MSwitch value={loading} onValueChange={setLoading} loading />
          <MSwitch value loading />
          <MSwitch value={disabled} onValueChange={setDisabled} disabled />
          <MSwitch value disabled />
        </div>
      </div>

      <div className="demo__block">
        <p className="demo__caption">change 事件</p>
        <div className="demo__row">
          <MSwitch
            value={changed}
            onValueChange={setChanged}
            inactiveText="bye"
            onChange={setLastChange}
          />
          <span className="demo__hint">change → {String(lastChange ?? "（还没切过）")}</span>
        </div>
      </div>

      <div className="demo__block">
        <p className="demo__caption">controlled：只发 change，值由外部延迟 600ms 再改</p>
        <div className="demo__row">
          <span>参数值为：{String(controlled)}</span>
          <MSwitch value={controlled} controlled onChange={onControlledChange} />
          <span className="demo__hint">想切到 → {String(asked ?? "—")}</span>
        </div>
      </div>

      <div className="demo__block">
        <p className="demo__caption">activeValue / inactiveValue：非布尔值</p>
        <div className="demo__row">
          <MSwitch
            value={mode}
            onValueChange={setMode}
            activeValue="night"
            inactiveValue="day"
            activeText="夜"
            inactiveText="昼"
          />
          <span className="demo__hint">mode = {String(mode)}</span>
        </div>
      </div>
    </div>
  );
}

// playground/src/demos/SwitchDemo.vue
<script setup lang="ts">
import { ref } from "vue";
import { MSwitch, type SwitchValue } from "@shuimo-design/ui";

const basic = ref(false);
const withText = ref(true);
const withSlot = ref(true);
const loading = ref(false);
const disabled = ref(false);
const changed = ref(false);
const lastChange = ref<SwitchValue>();
const controlled = ref(false);
const asked = ref<SwitchValue>();
const mode = ref<"day" | "night">("day");

function onControlledChange(next: SwitchValue) {
  // 受控：组件不自己改值，这里模拟"问过之后才切"
  asked.value = next;
  window.setTimeout(() => (controlled.value = next === true), 600);
}
</script>

<template>
  <div class="demo">
    <div class="demo__block">
      <p class="demo__caption">普通开关</p>
      <div class="demo__row">
        <span>参数值为：{{ basic }}</span>
        <MSwitch v-model="basic" />
      </div>
    </div>

    <div class="demo__block">
      <p class="demo__caption">activeText / inactiveText</p>
      <div class="demo__row">
        <MSwitch v-model="withText" active-text="active" inactive-text="inactive" />
      </div>
    </div>

    <div class="demo__block">
      <p class="demo__caption">slot 覆盖文字</p>
      <div class="demo__row">
        <MSwitch v-model="withSlot" active-text="active" inactive-text="inactive">
          <template #active>
            <span>这里是 active slot</span>
          </template>
        </MSwitch>
      </div>
    </div>

    <div class="demo__block">
      <p class="demo__caption">loading / disabled</p>
      <div class="demo__row">
        <MSwitch v-model="loading" loading />
        <MSwitch :model-value="true" loading />
        <MSwitch v-model="disabled" disabled />
        <MSwitch :model-value="true" disabled />
      </div>
    </div>

    <div class="demo__block">
      <p class="demo__caption">change 事件</p>
      <div class="demo__row">
        <MSwitch v-model="changed" inactive-text="bye" @change="lastChange = $event" />
        <span class="demo__hint">change → {{ lastChange ?? "（还没切过）" }}</span>
      </div>
    </div>

    <div class="demo__block">
      <p class="demo__caption">controlled：只发 change，值由外部延迟 600ms 再改</p>
      <div class="demo__row">
        <span>参数值为：{{ controlled }}</span>
        <MSwitch v-model="controlled" controlled @change="onControlledChange" />
        <span class="demo__hint">想切到 → {{ asked ?? "—" }}</span>
      </div>
    </div>

    <div class="demo__block">
      <p class="demo__caption">activeValue / inactiveValue：非布尔值</p>
      <div class="demo__row">
        <MSwitch
          v-model="mode"
          active-value="night"
          inactive-value="day"
          active-text="夜"
          inactive-text="昼"
        />
        <span class="demo__hint">mode = {{ mode }}</span>
      </div>
    </div>
  </div>
</template>
