// packages/ui/src/components/loading/MLoading.vue
<script setup lang="ts">
import "./loading.css";
import { computed } from "vue";
import { blobPoints } from "../../ink/assets/brush";
import { createRng } from "../../ink/random";
import type { LoadingProps, LoadingSlots } from "./types";

defineOptions({ name: "MLoading" });

const { speed = 2000, size = 40, mask = false, text, seed = 1 } = defineProps<LoadingProps>();
const slots = defineSlots<LoadingSlots>();

const DOTS = 8;
// 一笔转圈：八团毛边墨点沿圆周排开，从笔尾到笔头越来越大、越来越浓，转起来像一笔拖出的墨尾
const dots = computed(() => {
  const rng = createRng(seed * 13 + 5);
  return Array.from({ length: DOTS }, (_, i) => {
    const t = i / (DOTS - 1);
    const angle = (i / DOTS) * Math.PI * 2;
    return {
      points: blobPoints(
        24 + Math.cos(angle) * 15,
        24 + Math.sin(angle) * 15,
        2 + 3 * t,
        rng,
        0.18,
        32,
      ),
      opacity: (0.3 + 0.7 * t).toFixed(2),
    };
  });
});
const hasText = computed(() => Boolean(slots.default || text));
</script>

<template>
  <div
    class="m-loading"
    :class="{ 'm-loading--mask': mask }"
    :style="{ '--m-loading-speed': `${speed}ms`, '--m-loading-size': `${size}px` }"
    role="status"
    aria-live="polite"
    :aria-label="text ?? '加载中'"
  >
    <div class="m-loading__indicator">
      <slot name="indicator">
        <svg class="m-loading__spinner" viewBox="0 0 48 48" aria-hidden="true">
          <polygon
            v-for="(dot, i) in dots"
            :key="i"
            :points="dot.points"
            :fill-opacity="dot.opacity"
          />
        </svg>
      </slot>
    </div>
    <div v-if="hasText" class="m-loading__text">
      <slot>{{ text }}</slot>
    </div>
  </div>
</template>

// packages/react/src/components/loading/MLoading.tsx
import type { CSSProperties, ReactNode } from "react";
import {
  loadingClasses,
  loadingDots,
  loadingLabel,
  loadingVars,
  LOADING_VIEW_BOX,
  type LoadingProps as CoreLoadingProps,
} from "@shuimo-design/core";

export interface MLoadingProps extends CoreLoadingProps {
  /** 替换默认的墨点转圈指示器（对应 Vue 的 indicator 插槽） */
  indicator?: ReactNode;
  /** 替代 text（对应 Vue 的默认插槽） */
  children?: ReactNode;
  className?: string;
  style?: CSSProperties;
}

export function MLoading(props: MLoadingProps) {
  const { indicator, children, text } = props;
  // 墨点坐标是纯计算，放在 core；两个壳拿到的是同一串 points
  const dots = loadingDots(props);
  const hasText = Boolean(children || text);

  return (
    <div
      className={[...loadingClasses(props), props.className].filter(Boolean).join(" ")}
      style={{ ...loadingVars(props), ...props.style } as CSSProperties}
      role="status"
      aria-live="polite"
      aria-label={loadingLabel(props)}
    >
      <div className="m-loading__indicator">
        {indicator ?? (
          <svg className="m-loading__spinner" viewBox={LOADING_VIEW_BOX} aria-hidden="true">
            {dots.map((dot, i) => (
              <polygon key={i} points={dot.points} fillOpacity={dot.opacity} />
            ))}
          </svg>
        )}
      </div>
      {hasText ? <div className="m-loading__text">{children ?? text}</div> : null}
    </div>
  );
}
