// packages/vue/src/components/progress/MProgress.vue
<script setup lang="ts">
import { computed, useTemplateRef } from "vue";
import {
  progressBarStyle,
  progressBrush,
  progressClasses,
  progressShowInfo,
  progressValue,
  progressVars,
  type ProgressProps,
  type ProgressSlots,
} from "@shuimo-design/core";
import { useBrushBorder } from "../../ink";

defineOptions({ name: "MProgress" });

const {
  value,
  max,
  status,
  strokeWidth,
  // Vue 会把"没传的布尔 prop"转成 false，只有写成解构默认值才会登记进 props 的 default。
  // showInfo 的默认是 true，不在这里登记的话 core 分不清"没传"和"显式传了 false"
  showInfo = true,
} = defineProps<ProgressProps>();
defineSlots<ProgressSlots>();

const track = useTemplateRef<HTMLElement>("track");
useBrushBorder(track, progressBrush());

// core 的函数收整份 props，这里把解构出来的值重新组一份给它们（解构后仍是响应式的）
const props = computed<ProgressProps>(() => ({ value, max, status, strokeWidth, showInfo }));
// 钳制、取整全在 core，这里只把结果绑上去
const state = computed(() => progressValue(props.value));
</script>

<template>
  <div
    :class="progressClasses(props, state.percent)"
    :style="progressVars(props)"
    role="progressbar"
    :aria-valuenow="state.clamped"
    aria-valuemin="0"
    :aria-valuemax="state.max"
    :aria-valuetext="`${state.percent}%`"
  >
    <div ref="track" class="m-progress__track">
      <div class="m-progress__bar" :style="progressBarStyle(state.percent)" />
    </div>
    <!-- 文字压在条上居中：纸色字描一圈墨边，条走到字下面也看得清 -->
    <div v-if="progressShowInfo(props)" class="m-progress__info">
      <slot :percent="state.percent">{{ state.percent }}%</slot>
    </div>
  </div>
</template>

// packages/react/src/components/progress/MProgress.tsx
import type { CSSProperties, ReactNode } from "react";
import {
  progressBarStyle,
  progressBrush,
  progressClasses,
  progressShowInfo,
  progressValue,
  progressVars,
  type ProgressProps as CoreProgressProps,
} from "@shuimo-design/core";
import { useBrushBorder } from "../../ink";

export interface MProgressProps extends CoreProgressProps {
  /** 替代百分比文字；传函数时能拿到 percent（对应 Vue 的作用域插槽） */
  children?: ReactNode | ((props: { percent: number }) => ReactNode);
  className?: string;
  style?: CSSProperties;
}

export function MProgress(props: MProgressProps) {
  const { children } = props;
  const brushRef = useBrushBorder(progressBrush());
  // 钳制、取整、class 派生全在 core，这里只把结果绑上去
  const state = progressValue(props);

  const info =
    children === undefined
      ? `${state.percent}%`
      : typeof children === "function"
        ? children({ percent: state.percent })
        : children;

  return (
    <div
      className={[...progressClasses(props, state.percent), props.className]
        .filter(Boolean)
        .join(" ")}
      style={{ ...progressVars(props), ...props.style } as CSSProperties}
      role="progressbar"
      aria-valuenow={state.clamped}
      aria-valuemin={0}
      aria-valuemax={state.max}
      aria-valuetext={`${state.percent}%`}
    >
      <div ref={brushRef} className="m-progress__track">
        <div className="m-progress__bar" style={progressBarStyle(state.percent)} />
      </div>
      {/* 文字压在条上居中：纸色字描一圈墨边，条走到字下面也看得清 */}
      {progressShowInfo(props) ? <div className="m-progress__info">{info}</div> : null}
    </div>
  );
}
