// packages/react/src/components/ink-transition/MInkTransition.tsx
import { useMemo, type ReactElement } from "react";
import {
  INK_TRANSITION_NAME,
  inkTransitionHooks,
  type InkTransitionProps as CoreInkTransitionProps,
} from "@shuimo-design/core";
import { MTransition } from "../../transition";

export interface MInkTransitionProps extends Omit<CoreInkTransitionProps, "mode"> {
  /** 是否显示。对应 Vue 那边写在插槽里的 v-if */
  in: boolean;
  /** 要擦入 / 擦掉的那个元素，必须是单个能接 ref 的元素 */
  children: ReactElement;
}

/**
 * 墨迹转场：进入时从毛边遮罩里擦出来，离开时反向擦掉。
 *
 * 钩子来自 core 的 inkTransitionHooks，和 Vue 那边是同一份；这里只是把它们交给 MTransition。
 * css={false} 表示一个类名都不加 —— 这个组件的动画全在 Web Animations 里，没有对应的 CSS 规则。
 */
export function MInkTransition(props: MInkTransitionProps) {
  const {
    in: show,
    appear = false,
    children,
    duration,
    leaveDuration,
    seed,
    direction,
    raggedness,
    softness,
    reducedMotion,
  } = props;

  const hooks = useMemo(
    () =>
      inkTransitionHooks({
        duration,
        leaveDuration,
        seed,
        direction,
        raggedness,
        softness,
        reducedMotion,
      }),
    [duration, leaveDuration, seed, direction, raggedness, softness, reducedMotion],
  );

  return (
    <MTransition name={INK_TRANSITION_NAME} css={false} in={show} appear={appear} {...hooks}>
      {children}
    </MTransition>
  );
}

// packages/vue/src/components/ink-transition/MInkTransition.vue
<script setup lang="ts">
import { computed, Transition } from "vue";
import {
  inkTransitionHooks,
  type InkTransitionProps,
  type InkTransitionSlots,
} from "@shuimo-design/core";
import { toVueTransitionHooks } from "../../runtime/transition-hooks";

defineOptions({ name: "MInkTransition" });

// 必须直接解构 defineProps：先存成变量再解构，编译出来是 setup 期的一次性快照，props 改了不会重渲染。
// duration / leaveDuration / direction 这些的默认值在 core 的 inkTransitionHooks 里，这里不重复写
const {
  duration,
  leaveDuration,
  appear = false,
  mode = "default",
  seed,
  direction,
  raggedness,
  softness,
  reducedMotion,
} = defineProps<InkTransitionProps>();
defineSlots<InkTransitionSlots>();

// 落墨和擦除这两个钩子在 core 里，React 那边用的是同一份
const hooks = computed(() =>
  toVueTransitionHooks(
    inkTransitionHooks({
      duration,
      leaveDuration,
      seed,
      direction,
      raggedness,
      softness,
      reducedMotion,
    }),
  ),
);
</script>

<template>
  <!-- css: false —— 一个类名都不加，进出场完全由 JS 钩子里的 Web Animations 说了算 -->
  <Transition
    :css="false"
    :appear="appear"
    :mode="mode === 'default' ? undefined : mode"
    v-bind="hooks"
  >
    <slot />
  </Transition>
</template>
