// packages/vue/src/components/scroll/MScroll.vue
<script setup lang="ts">
import { computed, useTemplateRef, watchEffect } from "vue";
import {
  createScroll,
  scrollBarStyle,
  scrollClasses,
  scrollViewStyle,
  type ScrollEmits,
  type ScrollExpose,
  type ScrollProps,
  type ScrollSlots,
} from "@shuimo-design/core";
import { useController } from "../../runtime";

defineOptions({ name: "MScroll" });

const { height, maxHeight, always = false, minThumb = 20 } = defineProps<ScrollProps>();
const emit = defineEmits<ScrollEmits>();
defineSlots<ScrollSlots>();

// 滚动监听、尺寸监听、滑块拖拽、滚完淡出的定时器全在 core 的控制器里，和 React 那边是同一份
const { controller: scroll, state } = useController(createScroll, () => ({
  minThumb,
  onScroll: (position) => emit("scroll", position),
}));

const root = useTemplateRef<HTMLElement>("root");
const view = useTemplateRef<HTMLElement>("view");
const content = useTemplateRef<HTMLElement>("content");
const thumbV = useTemplateRef<HTMLElement>("thumbV");
const thumbH = useTemplateRef<HTMLElement>("thumbH");

// flush: "post" —— 等元素真的渲染出来再交给控制器；滑块是 v-if 出来的，这里会再跑一遍把它接上
watchEffect(
  () => {
    scroll.setRoot(root.value);
    scroll.setView(view.value);
    scroll.setContent(content.value);
    scroll.setThumb("v", thumbV.value);
    scroll.setThumb("h", thumbH.value);
  },
  { flush: "post" },
);

const rootClass = computed(() =>
  scrollClasses({ always, scrolling: state.value.scrolling, dragging: state.value.dragging }),
);
const viewStyle = computed(() => scrollViewStyle({ height, maxHeight }));
const barVStyle = computed(() => scrollBarStyle(state.value.v, "v"));
const barHStyle = computed(() => scrollBarStyle(state.value.h, "h"));

defineExpose<ScrollExpose>({
  scrollTo: scroll.scrollTo,
  update: scroll.measure,
  view: scroll.view,
});
</script>

<template>
  <div ref="root" :class="rootClass">
    <div ref="view" class="m-scroll__view" :style="viewStyle">
      <div ref="content" class="m-scroll__content">
        <slot />
      </div>
    </div>
    <div
      v-if="state.v.track > 0"
      class="m-scroll__bar m-scroll__bar--v"
      :style="barVStyle"
      aria-hidden="true"
    >
      <div ref="thumbV" class="m-scroll__thumb" />
    </div>
    <div
      v-if="state.h.track > 0"
      class="m-scroll__bar m-scroll__bar--h"
      :style="barHStyle"
      aria-hidden="true"
    >
      <div ref="thumbH" class="m-scroll__thumb" />
    </div>
  </div>
</template>

// packages/react/src/components/scroll/MScroll.tsx
import { useImperativeHandle, type CSSProperties, type ReactNode, type Ref } from "react";
import {
  createScroll,
  scrollBarStyle,
  scrollClasses,
  scrollViewStyle,
  type ScrollExpose,
  type ScrollPosition,
  type ScrollProps as CoreScrollProps,
} from "@shuimo-design/core";
import { useController } from "../../runtime";

export interface MScrollProps extends CoreScrollProps {
  /** 要滚动的内容 */
  children?: ReactNode;
  /** 视口滚动时触发，参数是当前滚动位置 */
  onScroll?: (position: ScrollPosition) => void;
  ref?: Ref<ScrollExpose>;
  className?: string;
  style?: CSSProperties;
}

export function MScroll(props: MScrollProps) {
  const { height, maxHeight, always = false, minThumb = 20, children } = props;

  // 滚动监听、尺寸监听、滑块拖拽、滚完淡出的定时器全在 core 的控制器里，和 Vue 那边是同一份
  const [scroll, state] = useController(createScroll, { minThumb, onScroll: props.onScroll });

  useImperativeHandle(
    props.ref,
    () => ({ scrollTo: scroll.scrollTo, update: scroll.measure, view: scroll.view }),
    [scroll],
  );

  return (
    // 控制器的方法身份恒定（控制器本身存在 ref 里），直接当 ref 回调用；
    // 换成渲染期新建的箭头函数，React 每次渲染都会先 ref(null) 再 ref(node)，白白重装一遍监听
    <div
      ref={scroll.setRoot}
      className={[
        ...scrollClasses({ always, scrolling: state.scrolling, dragging: state.dragging }),
        props.className,
      ]
        .filter(Boolean)
        .join(" ")}
      style={props.style}
    >
      <div
        ref={scroll.setView}
        className="m-scroll__view"
        style={scrollViewStyle({ height, maxHeight }) as CSSProperties}
      >
        <div ref={scroll.setContent} className="m-scroll__content">
          {children}
        </div>
      </div>
      {state.v.track > 0 ? (
        <div
          className="m-scroll__bar m-scroll__bar--v"
          style={scrollBarStyle(state.v, "v") as CSSProperties}
          aria-hidden="true"
        >
          <div ref={scroll.thumbRef("v")} className="m-scroll__thumb" />
        </div>
      ) : null}
      {state.h.track > 0 ? (
        <div
          className="m-scroll__bar m-scroll__bar--h"
          style={scrollBarStyle(state.h, "h") as CSSProperties}
          aria-hidden="true"
        >
          <div ref={scroll.thumbRef("h")} className="m-scroll__thumb" />
        </div>
      ) : null}
    </div>
  );
}
