// packages/react/src/components/alert/MAlert.tsx
import { useState, type CSSProperties, type MouseEvent, type ReactNode } from "react";
import {
  ALERT_CLOSE_LABEL,
  alertBarLine,
  alertClasses,
  alertStyle,
  collapseHeightHooks,
  type AlertProps as CoreAlertProps,
} from "@shuimo-design/core";
import { IconClose } from "../../icons";
import { MTransition } from "../../transition";
import { useBrushLine } from "../divider/use-brush-line";

export interface MAlertProps extends CoreAlertProps {
  /** 说明文字，优先于 description（对应 Vue 的默认插槽） */
  children?: ReactNode;
  /** 标题，优先于 title（对应 Vue 的 title 插槽） */
  titleNode?: ReactNode;
  /** 替换状态徽记 */
  icon?: ReactNode;
  /** 右侧操作区（按钮、链接） */
  action?: ReactNode;
  /** 点了关闭按钮；随后组件自己隐藏 */
  onClose?: (event: MouseEvent<HTMLElement>) => void;
  className?: string;
  style?: CSSProperties;
}

export function MAlert(props: MAlertProps) {
  const {
    type = "info",
    title,
    description,
    closable = true,
    showIcon = true,
    center = false,
    effect = "light",
    seed,
    children,
    titleNode,
    icon,
    action,
  } = props;

  const [visible, setVisible] = useState(true);
  const hasTitle = Boolean(titleNode || title);
  const hasDescription = Boolean(children || description);

  // 左边那条色边按整条提示的实际高度单独生成一根竖向笔触线，参数在 core
  const bar = useBrushLine(alertBarLine(seed));

  const onClose = (event: MouseEvent<HTMLElement>) => {
    setVisible(false);
    props.onClose?.(event);
  };

  return (
    /*
     * 收起过渡：离场只是把元素藏起来（unmountOnLeave=false，等同 Vue 的 v-show），
     * 得先把高度钉成实际值再过渡到 0。钉高度那几行在 core 的 collapseHeightHooks 里，
     * Vue 那边用的是同一份。
     */
    <MTransition name="m-alert" in={visible} unmountOnLeave={false} {...collapseHeightHooks}>
      <div
        className={[
          ...alertClasses({ type, effect, center, hasTitle, hasDescription }),
          props.className,
        ]
          .filter(Boolean)
          .join(" ")}
        style={{ ...alertStyle({ type, seed }), ...props.style } as CSSProperties}
        role="alert"
      >
        <span ref={bar} className="m-alert__bar" aria-hidden="true" />
        {showIcon ? (
          icon ? (
            <span className="m-alert__icon m-alert__icon--custom" aria-hidden="true">
              {icon}
            </span>
          ) : (
            <span className="m-alert__icon" aria-hidden="true" />
          )
        ) : null}
        <div className="m-alert__content">
          {hasTitle ? <div className="m-alert__title">{titleNode ?? title}</div> : null}
          {hasDescription ? (
            <div className="m-alert__description">{children ?? description}</div>
          ) : null}
        </div>
        {action ? <div className="m-alert__action">{action}</div> : null}
        {closable ? (
          <button
            type="button"
            className="m-alert__close"
            aria-label={ALERT_CLOSE_LABEL}
            onClick={onClose}
          >
            <IconClose />
          </button>
        ) : null}
      </div>
    </MTransition>
  );
}

// packages/vue/src/components/alert/MAlert.vue
<script setup lang="ts">
import { computed, ref, Transition, useTemplateRef } from "vue";
import {
  ALERT_CLOSE_LABEL,
  alertBarLine,
  alertClasses,
  alertStyle,
  collapseHeightHooks,
  type AlertEmits,
  type AlertProps,
  type AlertSlots,
} from "@shuimo-design/core";
import { IconClose } from "../../icons";
import { toVueTransitionHooks } from "../../runtime/transition-hooks";
import { useBrushLine } from "../divider/use-brush-line";

defineOptions({ name: "MAlert" });

// 必须直接解构 defineProps：先存成变量再解构，编译出来是 setup 期的一次性快照，props 改了不会重渲染
const {
  type = "info",
  title,
  description,
  closable = true,
  showIcon = true,
  center = false,
  effect = "light",
  seed,
} = defineProps<AlertProps>();
const emit = defineEmits<AlertEmits>();
const slots = defineSlots<AlertSlots>();

const visible = ref(true);
const hasTitle = computed(() => Boolean(slots.title || title));
const hasDescription = computed(() => Boolean(slots.default || description));

// 左边那条色边按整条提示的实际高度单独生成一根竖向笔触线，参数在 core
const bar = useTemplateRef<HTMLElement>("bar");
useBrushLine(bar, alertBarLine(seed));

const rootClass = computed(() =>
  alertClasses({
    type,
    effect,
    center,
    hasTitle: hasTitle.value,
    hasDescription: hasDescription.value,
  }),
);
const style = computed(() => alertStyle({ type, seed }));

/**
 * 收起过渡：v-show 只会瞬间 display:none，得先把高度钉成实际值再过渡到 0。
 * 钉高度那几行在 core 的 collapseHeightHooks 里（React 那边用的是同一份），
 * 这里只把它转接成 <Transition> 认的事件 props。
 */
const collapse = toVueTransitionHooks(collapseHeightHooks);

function onClose(event: MouseEvent) {
  visible.value = false;
  emit("close", event);
}
</script>

<template>
  <Transition name="m-alert" v-bind="collapse">
    <div v-show="visible" :class="rootClass" :style="style" role="alert">
      <span ref="bar" class="m-alert__bar" aria-hidden="true" />
      <template v-if="showIcon">
        <span v-if="slots.icon" class="m-alert__icon m-alert__icon--custom" aria-hidden="true">
          <slot name="icon" />
        </span>
        <span v-else class="m-alert__icon" aria-hidden="true" />
      </template>
      <div class="m-alert__content">
        <div v-if="hasTitle" class="m-alert__title">
          <slot name="title">{{ title }}</slot>
        </div>
        <div v-if="hasDescription" class="m-alert__description">
          <slot>{{ description }}</slot>
        </div>
      </div>
      <div v-if="slots.action" class="m-alert__action"><slot name="action" /></div>
      <button
        v-if="closable"
        type="button"
        class="m-alert__close"
        :aria-label="ALERT_CLOSE_LABEL"
        @click="onClose"
      >
        <IconClose />
      </button>
    </div>
  </Transition>
</template>
