// packages/react/src/components/radio/MRadio.tsx
import { useState, type CSSProperties, type ChangeEvent, type ReactNode } from "react";
import {
  radioChecked,
  radioClasses,
  radioDisabled,
  radioHasLabel,
  radioInk,
  radioNativeName,
  type RadioProps as CoreRadioProps,
} from "@shuimo-design/core";
import { useRadioGroup } from "./context";

export interface MRadioProps extends CoreRadioProps {
  /**
   * 受控选中态；不传就由组件自己记（配合 defaultChecked）。
   * 为什么不叫 `value`：`value` 已经被"这一项代表的值"占了（Vue 那边 v-model 是另一个通道），
   * 所以这一对沿用 React 原生 input 的 checked / defaultChecked。
   */
  checked?: boolean;
  defaultChecked?: boolean;
  /** 选中态变了（在组里时由组统一发，这里不发） */
  onCheckedChange?: (checked: boolean) => void;
  /** 用户操作选中了这一项 */
  onChange?: (value: CoreRadioProps["value"], event: ChangeEvent<HTMLInputElement>) => void;
  /** 文字，优先于 label */
  children?: ReactNode;
  className?: string;
  style?: CSSProperties;
}

export function MRadio(props: MRadioProps) {
  const { value, label, disabled: ownDisabled = false, name, children } = props;

  const group = useRadioGroup();
  // 受控 / 非受控两种都支持：传了 checked 就听外面的，没传就自己记一份
  const isControlled = props.checked !== undefined;
  const [uncontrolled, setUncontrolled] = useState(props.defaultChecked ?? false);
  const own = isControlled ? props.checked! : uncontrolled;

  // 在组里就比组的值；单独用时自己只记"选没选中"这一个布尔，
  // 转成 core 要的"当前选中的值"（没选就是 undefined）再比，两个壳走同一条判断
  const checked = radioChecked({ group, own: own ? value : undefined, value });
  const disabled = radioDisabled({ group, own: ownDisabled });
  const nativeName = radioNativeName({ group, name });

  // 外圈墨圈和中心墨点两张遮罩都在 core 里生成，和 Vue 那边是同一份
  const inkStyle = radioInk();

  function onChange(event: ChangeEvent<HTMLInputElement>) {
    if (disabled || !event.target.checked) return;
    if (group) {
      group.select(value);
    } else {
      if (!isControlled) setUncontrolled(true);
      props.onCheckedChange?.(true);
    }
    props.onChange?.(value, event);
  }

  return (
    <label
      className={[...radioClasses({ checked, disabled }), props.className]
        .filter(Boolean)
        .join(" ")}
      style={{ ...inkStyle, ...props.style } as CSSProperties}
    >
      <input
        className="m-radio__input"
        type="radio"
        name={nativeName}
        checked={checked}
        disabled={disabled}
        onChange={onChange}
      />
      <span className="m-radio__dot" aria-hidden="true" />
      {radioHasLabel(label, children !== undefined) ? (
        <span className="m-radio__label">{children ?? label}</span>
      ) : null}
    </label>
  );
}

// packages/vue/src/components/radio/MRadio.vue
<script setup lang="ts">
import { computed, inject } from "vue";
import {
  radioChecked,
  radioClasses,
  radioDisabled,
  radioHasLabel,
  radioInk,
  radioNativeName,
  type RadioEmits,
  type RadioProps,
  type RadioSlots,
  type RadioValue,
} from "@shuimo-design/core";
import { useDisabled, useFormItem } from "../../internal/form-item";
import { radioGroupKey } from "./context";

defineOptions({ name: "MRadio" });

const { value, label, disabled: disabledProp = false, name } = defineProps<RadioProps>();
const emit = defineEmits<RadioEmits>();
const slots = defineSlots<RadioSlots>();
const model = defineModel<RadioValue>();

const group = inject(radioGroupKey, undefined);
// 上下文形状在 core（context/form-item.ts），这两行只是 Vue 的 inject 胶水
const formItem = useFormItem();
const ownDisabled = useDisabled(() => disabledProp);

// 在组里就比组的值，单独用就比自己的 v-model；判断全在 core
const checked = computed(() => radioChecked({ group: group?.value, own: model.value, value }));
const disabled = computed(() => radioDisabled({ group: group?.value, own: ownDisabled.value }));
const nativeName = computed(() => radioNativeName({ group: group?.value, name }));
const classes = computed(() => radioClasses({ checked: checked.value, disabled: disabled.value }));

// 外圈墨圈和中心墨点两张遮罩都在 core 里生成，两个壳共用同一份
const inkStyle = radioInk();

function onChange(event: Event) {
  if (disabled.value || !(event.target as HTMLInputElement).checked) return;
  if (group) {
    group.value.select(value);
  } else {
    model.value = value;
  }
  emit("change", value, event);
  formItem.value.validate("change");
}
</script>

<template>
  <label :class="classes" :style="inkStyle">
    <input
      :id="group ? undefined : formItem.id"
      class="m-radio__input"
      type="radio"
      :name="nativeName"
      :checked="checked"
      :disabled="disabled"
      @change="onChange"
    />
    <span class="m-radio__dot" aria-hidden="true" />
    <span v-if="radioHasLabel(label, Boolean(slots.default))" class="m-radio__label">
      <slot>{{ label }}</slot>
    </span>
  </label>
</template>
