// packages/react/src/components/menu/MenuNode.tsx
import type { MenuTreeNode } from "@shuimo-design/core";
import { useMenuContext } from "./context";
import { MMenuItem } from "./MMenuItem";

/**
 * 递归渲染 data 整理出来的一层。
 *
 * Vue 那边要用一个函数组件把祖先的 label 插槽在层级里转发下去（插槽只能逐层传），
 * React 直接把 render prop 往下传就行 —— 这是纯框架手法，core 里不表达这件事。
 */
export function MenuNode({ node }: { node: MenuTreeNode }) {
  const menu = useMenuContext();
  return (
    <MMenuItem
      name={node.key}
      label={node.label}
      disabled={node.disabled}
      data={node.data}
      renderLabel={menu.renderLabel}
    >
      {node.children.length > 0
        ? node.children.map((child) => <MenuNode key={String(child.key)} node={child} />)
        : null}
    </MMenuItem>
  );
}

// packages/vue/src/components/menu/MenuNode.vue
<script setup lang="ts">
import type { FunctionalComponent } from "vue";
import type { MenuLabelScope, MenuTreeNode } from "@shuimo-design/core";
import { useMenuContext } from "./context";
import MMenuItem from "./MMenuItem.vue";

defineOptions({ name: "MenuNode" });

const { node } = defineProps<{ node: MenuTreeNode }>();

const menu = useMenuContext();

/** 用函数组件把 MMenu 的 label 插槽渲染出来，递归层级里不用逐层转发插槽 */
const Label: FunctionalComponent<MenuLabelScope> = (scope) => menu.renderLabel(scope);
</script>

<template>
  <MMenuItem :name="node.key" :label="node.label" :disabled="node.disabled" :data="node.data">
    <template #label="{ item, level }">
      <Label :item="item" :level="level" />
    </template>
    <template v-if="node.children.length > 0" #default>
      <MenuNode v-for="child in node.children" :key="child.key" :node="child" />
    </template>
  </MMenuItem>
</template>
