// packages/react/src/components/tabs/MTabs.tsx
import {
  Children,
  isValidElement,
  useCallback,
  useEffect,
  useId,
  useRef,
  useState,
  type CSSProperties,
  type KeyboardEvent,
  type MouseEvent,
  type ReactNode,
} from "react";
import {
  activeTabName,
  createTabsInk,
  fallbackTabName,
  focusTab,
  focusedTabIndex,
  isVerticalTabs,
  nextTabIndex,
  resolveTabs,
  tabIndicatorStyle,
  tabSlipBindings,
  tabsClasses,
  tabsContentBrush,
  tabsIndicatorOptions,
  tabsInkEnabled,
  tabsLineOptions,
  type TabName,
  type TabPaneConfig,
  type TabsProps as CoreTabsProps,
} from "@shuimo-design/core";
import { IconClose } from "../../icons";
import { useBrushBorder } from "../../ink";
import { useController, useMounted } from "../../runtime";
import { useBrushLine } from "../divider/use-brush-line";
import { MTabPane, type MTabPaneProps } from "./MTabPane";

/** React 这边的一页配置：标签和面板的内容就是普通的 ReactNode */
export type ReactTabPane = TabPaneConfig<ReactNode>;

export interface MTabsProps extends Omit<CoreTabsProps, "panes"> {
  /** 每一页的配置，顺序就是标签顺序；不传则按书写顺序从子组件 MTabPane 上收集 */
  panes?: ReactTabPane[];
  /** 受控的激活页；不传就由组件自己记（配合 defaultValue） */
  value?: TabName;
  defaultValue?: TabName;
  onValueChange?: (name: TabName) => void;
  /** 激活的标签变化 */
  onChange?: (name: TabName) => void;
  /** 点了某个标签（不管有没有真的切换） */
  onTabClick?: (name: TabName, event: MouseEvent) => void;
  /** 点了某个标签的关闭按钮；组件不会自己删 pane，由使用方处理 */
  onTabRemove?: (name: TabName) => void;
  /** 导航条末尾（横排时靠右，竖排时靠下）的附加内容 */
  extra?: ReactNode;
  /** 放 MTabPane（语法糖；传了 panes 就不看这里） */
  children?: ReactNode;
  className?: string;
  style?: CSSProperties;
}

/**
 * 从 children 里按**书写顺序**收集 MTabPane 的配置。
 *
 * 全程在渲染期完成：读的是元素上的 props，既不用等 effect、也不用比 DOM 位置。
 * effect 的执行顺序在 Fragment / Suspense / 并发切片下不保证跟 DOM 一致，
 * 服务端更是压根没有 DOM —— 这就是这三个组件不再用"子组件登记"的原因。
 */
function collectPanes(children: ReactNode): ReactTabPane[] {
  const panes: ReactTabPane[] = [];
  for (const node of Children.toArray(children)) {
    if (!isValidElement(node) || node.type !== MTabPane) continue;
    const props = node.props as MTabPaneProps;
    panes.push({
      // 没给 name 就用书写位置顶上；它只是个标识，value 也能拿它来切
      name: props.name ?? panes.length,
      label: props.label,
      labelNode: props.labelNode,
      disabled: props.disabled ?? false,
      closable: props.closable,
      lazy: props.lazy ?? false,
      content: props.children,
    });
  }
  return panes;
}

export function MTabs(props: MTabsProps) {
  const {
    type = "line",
    position = "top",
    closable = false,
    stretch = false,
    disabled = false,
    extra,
    children,
  } = props;

  const uid = useId();
  const vertical = isVerticalTabs(position);
  const card = type === "card";

  // 页的来源：传了 panes 就用传的，没传才从 children 收集
  const panes = props.panes ?? collectPanes(children);

  const controlled = props.value !== undefined;
  const [uncontrolled, setUncontrolled] = useState<TabName | undefined>(props.defaultValue);
  const model = controlled ? props.value : uncontrolled;
  const active = activeTabName(panes, model);
  const tabs = resolveTabs({ panes, active, uid, closable, disabled });

  const setActive = useCallback(
    (name: TabName) => {
      if (name === active) return;
      if (!controlled) setUncontrolled(name);
      props.onValueChange?.(name);
      props.onChange?.(name);
    },
    // props 每次渲染都是新对象，只盯真正会改变行为的两个值
    // eslint-disable-next-line react-hooks/exhaustive-deps
    [controlled, active],
  );

  /** 记住激活项的位置：value 指向的页被删掉时，像浏览器关标签一样落到邻居上 */
  const lastIndex = useRef(0);
  const activeIndex = tabs.findIndex((tab) => tab.active);
  useEffect(() => {
    if (activeIndex >= 0) {
      lastIndex.current = activeIndex;
      return;
    }
    if (model === undefined || panes.length === 0) return;
    const next = fallbackTabName(panes, lastIndex.current);
    if (next !== undefined) setActive(next);
  });

  /** lazy 的页记住"已经激活过"，之后切走只隐藏不销毁 */
  const opened = useRef(new Set<TabName>());
  if (active !== undefined) opened.current.add(active);

  // ---- 量导航条：指示器位置、签条底图、激活签条的三面框全在 core 的控制器里 ----
  const [ink, state] = useController(createTabsInk, { vertical, card, position });
  const listEl = useRef<HTMLElement | null>(null);
  const setList = useCallback(
    (el: HTMLDivElement | null) => {
      listEl.current = el;
      ink.setList(el);
    },
    [ink],
  );
  // 每轮渲染之后重量一次：激活项、页数、方向、外形变了都要跟
  useEffect(() => ink.measure());

  /** 挂载后才敢走素材登记（服务端登记不了），首帧一律内联，两边输出才对得上 */
  const mounted = useMounted();

  // ---- line 型的两条线：整长的底线按导航条长度生成，指示器按激活项宽度单独生成 ----
  const lineRef = useBrushLine({ ...tabsLineOptions(), vertical });
  const indicatorRef = useBrushLine({ ...tabsIndicatorOptions(), vertical });
  // 内容区四面框，签条插进它的上沿；stroke.css 只在 html.m-ink-ready 下生效
  const contentRef = useBrushBorder({ ...tabsContentBrush(), enabled: tabsInkEnabled(card) });

  function onKeyDown(event: KeyboardEvent<HTMLElement>) {
    if (disabled) return;
    const focused = focusedTabIndex(listEl.current, event.target);
    const from = focused >= 0 ? focused : activeIndex;
    const next = nextTabIndex(panes, { key: event.key, vertical, from });
    if (next === undefined) return;
    event.preventDefault();
    focusTab(listEl.current, next);
    const pane = panes[next];
    if (pane) setActive(pane.name);
  }

  return (
    <div
      className={[...tabsClasses({ type, position, stretch, disabled }), props.className]
        .filter(Boolean)
        .join(" ")}
      style={props.style}
    >
      <div className="m-tabs__nav">
        <div
          ref={setList}
          className="m-tabs__list"
          role="tablist"
          aria-orientation={vertical ? "vertical" : "horizontal"}
          onKeyDown={onKeyDown}
        >
          {tabs.map((tab) => {
            const slip = tabSlipBindings(state.slips[tab.tabId], mounted);
            return (
              <div
                key={tab.name}
                id={tab.tabId}
                className={[
                  "m-tabs__tab",
                  tab.active ? "m-tabs__tab--active" : "",
                  tab.disabled ? "m-tabs__tab--disabled" : "",
                  tab.closable ? "m-tabs__tab--closable" : "",
                ]
                  .filter(Boolean)
                  .join(" ")}
                role="tab"
                aria-selected={tab.active}
                aria-controls={tab.panelId}
                aria-disabled={tab.disabled || undefined}
                tabIndex={tab.active && !tab.disabled ? 0 : -1}
                style={slip.style as CSSProperties}
                {...slip.attrs}
                onClick={(event) => {
                  if (tab.disabled) return;
                  props.onTabClick?.(tab.name, event);
                  setActive(tab.name);
                }}
                onKeyDown={(event) => {
                  if (event.key !== "Enter" && event.key !== " ") return;
                  event.preventDefault();
                  setActive(tab.name);
                }}
              >
                <span className="m-tabs__label">{panes[tab.index]?.labelNode ?? tab.label}</span>
                {tab.closable ? (
                  <button
                    type="button"
                    className="m-tabs__close"
                    aria-label={tab.closeLabel}
                    disabled={tab.disabled}
                    tabIndex={-1}
                    onClick={(event) => {
                      event.stopPropagation();
                      if (tab.disabled) return;
                      props.onTabRemove?.(tab.name);
                    }}
                  >
                    <IconClose />
                  </button>
                ) : null}
              </div>
            );
          })}
          {/* 指示器放在列表里，位移直接用标签相对列表的 offset */}
          {type === "line" ? (
            <span
              ref={indicatorRef}
              className="m-tabs__indicator"
              style={tabIndicatorStyle(state.indicator, vertical) as CSSProperties}
              aria-hidden="true"
            />
          ) : null}
        </div>
        {extra ? <div className="m-tabs__extra">{extra}</div> : null}
        {/* 底线跨整个导航条（含 extra），所以放在 nav 上而不是列表里 */}
        {type === "line" ? (
          <span ref={lineRef} className="m-tabs__line" aria-hidden="true" />
        ) : null}
      </div>
      <div ref={contentRef} className="m-tabs__content">
        {tabs.map((tab) => {
          const pane = panes[tab.index];
          const render = !pane?.lazy || opened.current.has(tab.name);
          return (
            <div
              key={tab.name}
              id={tab.panelId}
              className="m-tab-pane"
              role="tabpanel"
              aria-labelledby={tab.tabId}
              aria-hidden={!tab.active}
              // 和 Vue 的 v-show 一样用内联 display 藏起来（不用 hidden 属性：
              // 组件样式里一旦给 .m-tab-pane 设了 display，UA 的 [hidden] 就压不住了）
              style={tab.active ? undefined : { display: "none" }}
            >
              {render ? pane?.content : null}
            </div>
          );
        })}
      </div>
    </div>
  );
}

// packages/vue/src/components/tabs/MTabs.vue
<script setup lang="ts">
import { computed, onMounted, reactive, ref, useId, useSlots, useTemplateRef, watch } from "vue";
import {
  activeTabName,
  createTabsInk,
  fallbackTabName,
  focusTab,
  focusedTabIndex,
  isVerticalTabs,
  nextTabIndex,
  resolveTabs,
  tabIndicatorStyle,
  tabSlipBindings,
  tabsClasses,
  tabsContentBrush,
  tabsInkEnabled,
  tabsIndicatorOptions,
  tabsLineOptions,
  type TabName,
  type TabsEmits,
  type TabsProps,
  type TabsSlots,
} from "@shuimo-design/core";
import { IconClose } from "../../icons";
import { useBrushBorder } from "../../ink";
import { useController } from "../../runtime";
import { RenderNode } from "../../runtime/render-node";
import { useBrushLine } from "../divider/use-brush-line";
import { collectPanes, type MTabsProps, type VueTabPane } from "./collect";

defineOptions({ name: "MTabs" });

const {
  panes: panesProp,
  type = "line",
  position = "top",
  closable = false,
  stretch = false,
  disabled = false,
} = defineProps<MTabsProps>();
const emit = defineEmits<TabsEmits>();
const slots = useSlots() as TabsSlots;
defineSlots<TabsSlots>();
const model = defineModel<TabName>();

const uid = useId();
const vertical = computed(() => isVerticalTabs(position));
const card = computed(() => type === "card");

/**
 * 页的来源：传了 panes 就用传的，没传才从子组件收集。
 * 收集在渲染期完成（读 vnode 的 props），顺序 = 模板里的书写顺序。
 */
const panes = computed<VueTabPane[]>(() => panesProp ?? collectPanes(slots.default?.()));

const activeName = computed(() => activeTabName(panes.value, model.value));
const tabs = computed(() =>
  resolveTabs({ panes: panes.value, active: activeName.value, uid, closable, disabled }),
);

function setActive(name: TabName) {
  if (name === activeName.value) return;
  model.value = name;
  emit("change", name);
}

/** 记住激活项的位置：v-model 指向的页被删掉时，像浏览器关标签一样落到邻居上 */
let lastIndex = 0;
watch(
  tabs,
  (list) => {
    const index = list.findIndex((tab) => tab.active);
    if (index >= 0) {
      lastIndex = index;
      return;
    }
    if (model.value === undefined || list.length === 0) return;
    const next = fallbackTabName(panes.value, lastIndex);
    if (next !== undefined) setActive(next);
  },
  { immediate: true },
);

/** lazy 的页记住"已经激活过"，之后切走只隐藏不销毁 */
const opened = reactive(new Set<TabName>());
watch(
  activeName,
  (name) => {
    if (name !== undefined) opened.add(name);
  },
  { immediate: true },
);
function shouldRender(index: number, name: TabName): boolean {
  return !panes.value[index]?.lazy || opened.has(name);
}

function onTabClick(tab: { index: number; name: TabName; disabled: boolean }, event: MouseEvent) {
  if (tab.disabled) return;
  emit("tabClick", tab.name, event);
  setActive(tab.name);
}

function onRemove(tab: { name: TabName; disabled: boolean }, event: MouseEvent) {
  event.stopPropagation();
  if (tab.disabled) return;
  emit("tabRemove", tab.name);
}

// ---- 键盘：roving tabindex，方向键在可用标签间循环，Home / End 跳到两头 ----
const list = useTemplateRef<HTMLElement>("list");

function onKeydown(event: KeyboardEvent) {
  if (disabled) return;
  const focused = focusedTabIndex(list.value, event.target);
  const from = focused >= 0 ? focused : tabs.value.findIndex((tab) => tab.active);
  const next = nextTabIndex(panes.value, { key: event.key, vertical: vertical.value, from });
  if (next === undefined) return;
  event.preventDefault();
  focusTab(list.value, next);
  const pane = panes.value[next];
  if (pane) setActive(pane.name);
}

// ---- line 型的两条线：整长的底线按导航条长度生成，指示器按激活项宽度单独生成 ----
const line = useTemplateRef<HTMLElement>("line");
const indicator = useTemplateRef<HTMLElement>("indicator");
useBrushLine(line, { ...tabsLineOptions(), vertical: () => vertical.value });
useBrushLine(indicator, { ...tabsIndicatorOptions(), vertical: () => vertical.value });

// 内容区四面框，签条插进它的上沿；stroke.css 只在 html.m-ink-ready 下生效
const content = useTemplateRef<HTMLElement>("content");
useBrushBorder(content, {
  ...tabsContentBrush(),
  enabled: computed(() => tabsInkEnabled(card.value)),
});

// ---- 量导航条：指示器位置、签条底图、激活签条的三面框全在 core 的控制器里 ----
const { controller: ink, state } = useController(createTabsInk, () => ({
  vertical: vertical.value,
  card: card.value,
  position,
}));

/** 挂载后才敢走素材登记（服务端登记不了），首帧一律内联，两边输出才对得上 */
const mounted = ref(false);
watch(list, (el) => ink.setList(el), { immediate: true, flush: "post" });
onMounted(() => {
  mounted.value = true;
  ink.measure();
});
// 激活项、页数、方向、外形变了都要重量；flush post 保证 DOM 已经换好 active 类
watch([activeName, () => panes.value.length, () => position, card], () => ink.measure(), {
  flush: "post",
});

const indicatorCss = computed(() => tabIndicatorStyle(state.value.indicator, vertical.value));
function slip(tabId: string) {
  return tabSlipBindings(state.value.slips[tabId], mounted.value);
}
</script>

<template>
  <div class="m-tabs" :class="tabsClasses({ type, position, stretch, disabled })">
    <div class="m-tabs__nav">
      <div
        ref="list"
        class="m-tabs__list"
        role="tablist"
        :aria-orientation="vertical ? 'vertical' : 'horizontal'"
        @keydown="onKeydown"
      >
        <div
          v-for="tab in tabs"
          :id="tab.tabId"
          :key="tab.name"
          class="m-tabs__tab"
          :class="{
            'm-tabs__tab--active': tab.active,
            'm-tabs__tab--disabled': tab.disabled,
            'm-tabs__tab--closable': tab.closable,
          }"
          role="tab"
          :aria-selected="tab.active"
          :aria-controls="tab.panelId"
          :aria-disabled="tab.disabled || undefined"
          :tabindex="tab.active && !tab.disabled ? 0 : -1"
          :style="slip(tab.tabId).style"
          v-bind="slip(tab.tabId).attrs"
          @click="onTabClick(tab, $event)"
          @keydown.enter.space.prevent="setActive(tab.name)"
        >
          <span class="m-tabs__label">
            <RenderNode
              v-if="panes[tab.index]?.labelNode !== undefined"
              :node="panes[tab.index]!.labelNode"
            />
            <template v-else>{{ tab.label }}</template>
          </span>
          <button
            v-if="tab.closable"
            type="button"
            class="m-tabs__close"
            :aria-label="tab.closeLabel"
            :disabled="tab.disabled"
            tabindex="-1"
            @click="onRemove(tab, $event)"
          >
            <IconClose />
          </button>
        </div>
        <!-- 指示器放在列表里，位移直接用标签相对列表的 offset -->
        <span
          v-if="type === 'line'"
          ref="indicator"
          class="m-tabs__indicator"
          :style="indicatorCss"
          aria-hidden="true"
        />
      </div>
      <div v-if="$slots.extra" class="m-tabs__extra"><slot name="extra" /></div>
      <!-- 底线跨整个导航条（含 extra），所以放在 nav 上而不是列表里 -->
      <span v-if="type === 'line'" ref="line" class="m-tabs__line" aria-hidden="true" />
    </div>
    <div ref="content" class="m-tabs__content">
      <div
        v-for="tab in tabs"
        v-show="tab.active"
        :id="tab.panelId"
        :key="tab.name"
        class="m-tab-pane"
        role="tabpanel"
        :aria-labelledby="tab.tabId"
        :aria-hidden="!tab.active"
      >
        <RenderNode
          v-if="shouldRender(tab.index, tab.name) && panes[tab.index]?.content !== undefined"
          :node="panes[tab.index]!.content"
        />
      </div>
    </div>
  </div>
</template>
