// packages/react/src/components/rice-paper/MRicePaper.tsx
import { useCallback, useEffect, type CSSProperties, type ReactNode } from "react";
import {
  createRicePaper,
  ricePaperBaseColor,
  ricePaperClasses,
  ricePaperRidges,
  ricePaperSeed,
  ricePaperShowLandscape,
  ricePaperStyle,
  ricePaperTier,
  type RicePaperProps as CoreRicePaperProps,
  type RicePaperReadyPayload,
} from "@shuimo-design/core";
import { useController } from "../../runtime";

export interface MRicePaperProps extends CoreRicePaperProps {
  /** 纸上的内容 */
  children?: ReactNode;
  /** 纹理（和洒金）解码完成、纸可以淡入时调一次 */
  onReady?: (payload: RicePaperReadyPayload) => void;
  className?: string;
  style?: CSSProperties;
}

export function MRicePaper(props: MRicePaperProps) {
  const {
    seed,
    tier: tierProp,
    paper,
    grain = 0.5,
    goldFlecks = false,
    fibers = 1,
    particles = 0.5,
    deckleEdge = false,
    landscape = true,
    parallax = true,
    layout = "auto",
    children,
  } = props;

  /*
   * 检测特效档位、从 --m-paper-rgb 读纸色、盯 data-theme 和系统深浅偏好、量尺寸、
   * 等纹理解码完再淡入、给远山挂视差 —— 全在 core 的控制器里，Vue 那边用的是同一份。
   */
  const [controller, state] = useController(createRicePaper, {
    seed,
    tier: tierProp,
    paper,
    grain,
    fibers,
    particles,
    goldFlecks,
    deckleEdge,
    landscape,
    parallax,
    onReady: props.onReady,
  });

  // ref 回调的身份必须稳定：变了 React 会先 ref(null) 再 ref(node)，控制器会白白重来一遍
  const ref = useCallback((el: HTMLElement | null) => controller.attach(el), [controller]);
  // 远山是条件渲染的，元素什么时候在树上只有壳知道；每轮渲染落地后告诉控制器一次，它自己比对有没有变
  useEffect(() => {
    controller.sync();
  });

  const resolvedSeed = ricePaperSeed(seed, state.fallbackSeed);
  const tier = ricePaperTier(tierProp, state.detectedTier);
  const baseColor = ricePaperBaseColor(paper, state.themePaper);
  const showLandscape = ricePaperShowLandscape(landscape, tier);
  // 远山的图只在挂载后生成：几百 KB 不进服务端 HTML，反正要等 ready 才淡入
  const ridges = showLandscape && state.mounted ? ricePaperRidges(resolvedSeed) : [];

  const ink = ricePaperStyle({
    tier,
    seed: resolvedSeed,
    baseColor,
    grain,
    fibers,
    particles,
    goldFlecks,
    deckleEdge,
    width: state.width,
    height: state.height,
  });

  return (
    <div
      ref={ref}
      className={[
        ...ricePaperClasses({ ready: state.ready, deckleEdge, layout, showLandscape, tier }),
        props.className,
      ]
        .filter(Boolean)
        .join(" ")}
      data-seed={resolvedSeed}
      style={{ ...ink, ...props.style } as CSSProperties}
    >
      {showLandscape ? (
        <div className="m-rice-paper__landscape" aria-hidden="true">
          {ridges.map((ridge) => (
            <div
              key={ridge.key}
              className={`m-rice-paper__ridge ${ridge.className}`}
              style={ridge.style as CSSProperties}
            >
              <span className="m-rice-paper__ridge-wash" />
              <span className="m-rice-paper__ridge-line" />
            </div>
          ))}
        </div>
      ) : null}
      <div className="m-rice-paper__content">{children}</div>
    </div>
  );
}

// packages/vue/src/components/rice-paper/MRicePaper.vue
<script setup lang="ts">
import { computed, onMounted, useTemplateRef, watchEffect } from "vue";
import {
  createRicePaper,
  ricePaperBaseColor,
  ricePaperClasses,
  ricePaperRidges,
  ricePaperSeed,
  ricePaperShowLandscape,
  ricePaperStyle,
  ricePaperTier,
  type RicePaperEmits,
  type RicePaperProps,
  type RicePaperSlots,
} from "@shuimo-design/core";
import { useController } from "../../runtime";

defineOptions({ name: "MRicePaper" });

// 必须直接解构 defineProps：先存成变量再解构，编译出来是 setup 期的一次性快照，props 改了不会重渲染
const {
  seed,
  tier: tierProp,
  paper,
  grain = 0.5,
  goldFlecks = false,
  fibers = 1,
  particles = 0.5,
  deckleEdge = false,
  landscape = true,
  parallax = true,
  layout = "auto",
} = defineProps<RicePaperProps>();
const emit = defineEmits<RicePaperEmits>();
defineSlots<RicePaperSlots>();

const root = useTemplateRef<HTMLElement>("root");

/*
 * 检测特效档位、从 --m-paper-rgb 读纸色、盯 data-theme 和系统深浅偏好、量尺寸、
 * 等纹理解码完再淡入、给远山挂视差 —— 全在 core 的控制器里，React 那边用的是同一份。
 */
const { controller, state } = useController(createRicePaper, () => ({
  seed,
  tier: tierProp,
  paper,
  grain,
  fibers,
  particles,
  goldFlecks,
  deckleEdge,
  landscape,
  parallax,
  onReady: (payload) => emit("ready", payload),
}));

const resolvedSeed = computed(() => ricePaperSeed(seed, state.value.fallbackSeed));
const tier = computed(() => ricePaperTier(tierProp, state.value.detectedTier));
const baseColor = computed(() => ricePaperBaseColor(paper, state.value.themePaper));
const showLandscape = computed(() => ricePaperShowLandscape(landscape, tier.value));
// 远山的图只在挂载后生成：几百 KB 不进服务端 HTML，反正要等 ready 才淡入
const ridges = computed(() =>
  showLandscape.value && state.value.mounted ? ricePaperRidges(resolvedSeed.value) : [],
);

const rootClass = computed(() =>
  ricePaperClasses({
    ready: state.value.ready,
    deckleEdge,
    layout,
    showLandscape: showLandscape.value,
    tier: tier.value,
  }),
);
const style = computed(() =>
  ricePaperStyle({
    tier: tier.value,
    seed: resolvedSeed.value,
    baseColor: baseColor.value,
    grain,
    fibers,
    particles,
    goldFlecks,
    deckleEdge,
    width: state.value.width,
    height: state.value.height,
  }),
);

onMounted(() => {
  controller.attach(root.value);
  // 远山在 v-if / v-for 里，元素什么时候在树上只有壳知道；flush: "post" 等这一轮 DOM 更新完再告诉控制器
  watchEffect(
    () => {
      void ridges.value;
      void parallax;
      controller.sync();
    },
    { flush: "post" },
  );
});
</script>

<template>
  <div ref="root" :class="rootClass" :data-seed="resolvedSeed" :style="style">
    <div v-if="showLandscape" class="m-rice-paper__landscape" aria-hidden="true">
      <div
        v-for="ridge in ridges"
        :key="ridge.key"
        class="m-rice-paper__ridge"
        :class="ridge.className"
        :style="ridge.style"
      >
        <span class="m-rice-paper__ridge-wash" />
        <span class="m-rice-paper__ridge-line" />
      </div>
    </div>
    <div class="m-rice-paper__content"><slot /></div>
  </div>
</template>
