// packages/vue/src/components/button/MButton.vue
<script setup lang="ts">
import { computed, onMounted, ref, useTemplateRef } from "vue";
import {
  buttonBrush,
  buttonClasses,
  buttonInert,
  buttonInk,
  isSolidButton,
  type ButtonEmits,
  type ButtonProps,
  type ButtonSlots,
} from "@shuimo-design/core";
import { observeSize } from "@shuimo-design/core";
import { IconLoading } from "../../icons";
import { useBrushBorder } from "../../ink";

defineOptions({ name: "MButton" });

const props = defineProps<ButtonProps>();
const {
  type = "default",
  text = "",
  disabled = false,
  loading = false,
  href,
  nativeType = "button",
} = props;
const emit = defineEmits<ButtonEmits>();
defineSlots<ButtonSlots>();

const root = useTemplateRef<HTMLElement>("root");
const solid = computed(() => isSolidButton(type));
useBrushBorder(root, buttonBrush(solid.value));

// 毛边色块要按按钮实际尺寸生成，只能挂载后量；服务端和水合首帧都是 0×0，渲染出的是没有色块的朴素版
const size = ref({ width: 0, height: 0 });
const mounted = ref(false);
onMounted(() => {
  mounted.value = true;
  if (root.value) observeSize(root.value, (box) => (size.value = box), "border-box");
});

const ink = computed(() =>
  buttonInk({
    solid: solid.value,
    width: size.value.width,
    height: size.value.height,
    registered: mounted.value,
  }),
);

function onClick(event: MouseEvent) {
  if (buttonInert(props)) {
    event.preventDefault();
    return;
  }
  emit("click", event);
}
</script>

<template>
  <component
    :is="href ? 'a' : 'button'"
    ref="root"
    :class="buttonClasses(props)"
    :style="ink.style"
    v-bind="ink.attrs"
    :href="href"
    :type="href ? undefined : nativeType"
    :disabled="href ? undefined : disabled"
    :aria-disabled="disabled || undefined"
    :aria-busy="loading || undefined"
    @click="onClick"
  >
    <IconLoading v-if="loading" class="m-button__spinner" />
    <span class="m-button__label"
      ><slot>{{ text }}</slot></span
    >
  </component>
</template>

// packages/react/src/components/button/MButton.tsx
import { useMemo, type MouseEvent, type ReactNode } from "react";
import {
  buttonBrush,
  buttonClasses,
  buttonInert,
  buttonInk,
  isSolidButton,
  type ButtonProps as CoreButtonProps,
} from "@shuimo-design/core";
import { IconLoading } from "../../icons";
import { useBrushBorder } from "../../ink";
import { useMounted, useSize } from "../../runtime";

export interface MButtonProps extends CoreButtonProps {
  children?: ReactNode;
  onClick?: (event: MouseEvent<HTMLElement>) => void;
  className?: string;
  style?: React.CSSProperties;
}

export function MButton(props: MButtonProps) {
  const {
    type = "default",
    text = "",
    disabled = false,
    loading = false,
    href,
    nativeType = "button",
  } = props;
  const solid = isSolidButton(type);
  const brushRef = useBrushBorder(buttonBrush(solid));
  const [sizeRef, size] = useSize("border-box");
  const mounted = useMounted();

  // 两个 ref 回调合成一个绑到根元素上
  const ref = useMemo(
    () => (el: HTMLElement | null) => {
      brushRef(el);
      sizeRef(el);
    },
    [brushRef, sizeRef],
  );

  const ink = buttonInk({ solid, width: size.width, height: size.height, registered: mounted });

  const onClick = (event: MouseEvent<HTMLElement>) => {
    if (buttonInert(props)) {
      event.preventDefault();
      return;
    }
    props.onClick?.(event);
  };

  const shared = {
    ref: ref as never,
    className: [...buttonClasses(props), props.className].filter(Boolean).join(" "),
    style: { ...ink.style, ...props.style } as React.CSSProperties,
    ...ink.attrs,
    "aria-disabled": disabled || undefined,
    "aria-busy": loading || undefined,
    onClick,
  };

  const body = (
    <>
      {loading ? <IconLoading className="m-button__spinner" /> : null}
      <span className="m-button__label">{props.children ?? text}</span>
    </>
  );

  return href ? (
    <a {...shared} href={href}>
      {body}
    </a>
  ) : (
    <button {...shared} type={nativeType} disabled={disabled}>
      {body}
    </button>
  );
}
